from PyQt5 import QtCore, QtGui, QtWidgets


# noinspection PyUnresolvedReferences
class Ui_WMML_train(object):
    def setupUi(self, WMML_train):
        WMML_train.setObjectName("WMML_train")
        WMML_train.resize(730, 660)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(WMML_train.sizePolicy().hasHeightForWidth())
        WMML_train.setSizePolicy(sizePolicy)
        WMML_train.setMinimumSize(QtCore.QSize(500, 500))
        self.verticalLayout = QtWidgets.QVBoxLayout(WMML_train)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(WMML_train)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_6 = QtWidgets.QLabel(self.tab_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_14.addWidget(self.label_6)
        self.jz_fd_tab = QtWidgets.QTableView(self.tab_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.jz_fd_tab.sizePolicy().hasHeightForWidth())
        self.jz_fd_tab.setSizePolicy(sizePolicy)
        self.jz_fd_tab.setSizeIncrement(QtCore.QSize(0, 20))
        self.jz_fd_tab.setObjectName("jz_fd_tab")
        self.verticalLayout_14.addWidget(self.jz_fd_tab)
        self.horizontalLayout_6.addLayout(self.verticalLayout_14)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setSpacing(0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_7 = QtWidgets.QLabel(self.tab_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_15.addWidget(self.label_7)
        self.jz_td_tab = QtWidgets.QTableView(self.tab_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.jz_td_tab.sizePolicy().hasHeightForWidth())
        self.jz_td_tab.setSizePolicy(sizePolicy)
        self.jz_td_tab.setSizeIncrement(QtCore.QSize(0, 20))
        self.jz_td_tab.setObjectName("jz_td_tab")
        self.verticalLayout_15.addWidget(self.jz_td_tab)
        self.horizontalLayout_6.addLayout(self.verticalLayout_15)
        self.horizontalLayout_6.setStretch(0, 6)
        self.horizontalLayout_6.setStretch(1, 2)
        self.gridLayout_11.addLayout(self.horizontalLayout_6, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setSpacing(0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.ml_tr_fig = QtWidgets.QGridLayout()
        self.ml_tr_fig.setObjectName("ml_tr_fig")
        self.gridLayout_9.addLayout(self.ml_tr_fig, 0, 0, 1, 1)
        self.verticalLayout_12.addWidget(self.groupBox_5)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.ml_param_tab3 = QtWidgets.QTextBrowser(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ml_param_tab3.sizePolicy().hasHeightForWidth())
        self.ml_param_tab3.setSizePolicy(sizePolicy)
        self.ml_param_tab3.setMinimumSize(QtCore.QSize(0, 75))
        self.ml_param_tab3.setMaximumSize(QtCore.QSize(16777215, 75))
        self.ml_param_tab3.setObjectName("ml_param_tab3")
        self.gridLayout_7.addWidget(self.ml_param_tab3, 2, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        self.label_20.setObjectName("label_20")
        self.gridLayout_7.addWidget(self.label_20, 0, 0, 1, 1)
        self.verticalLayout_12.addLayout(self.gridLayout_7)
        self.horizontalLayout_5.addLayout(self.verticalLayout_12)
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_60 = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_60.sizePolicy().hasHeightForWidth())
        self.label_60.setSizePolicy(sizePolicy)
        self.label_60.setObjectName("label_60")
        self.gridLayout_8.addWidget(self.label_60, 0, 0, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_44.sizePolicy().hasHeightForWidth())
        self.label_44.setSizePolicy(sizePolicy)
        self.label_44.setObjectName("label_44")
        self.gridLayout_8.addWidget(self.label_44, 0, 1, 1, 1)
        self.ml_param_tab4 = QtWidgets.QTextBrowser(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ml_param_tab4.sizePolicy().hasHeightForWidth())
        self.ml_param_tab4.setSizePolicy(sizePolicy)
        self.ml_param_tab4.setObjectName("ml_param_tab4")
        self.gridLayout_8.addWidget(self.ml_param_tab4, 1, 0, 1, 1)
        self.tr_pd_tab = QtWidgets.QTableView(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tr_pd_tab.sizePolicy().hasHeightForWidth())
        self.tr_pd_tab.setSizePolicy(sizePolicy)
        self.tr_pd_tab.setObjectName("tr_pd_tab")
        self.gridLayout_8.addWidget(self.tr_pd_tab, 1, 1, 1, 1)
        self.gridLayout_8.setColumnStretch(0, 3)
        self.gridLayout_8.setColumnStretch(1, 5)
        self.horizontalLayout_5.addLayout(self.gridLayout_8)
        self.horizontalLayout_5.setStretch(0, 5)
        self.horizontalLayout_5.setStretch(1, 4)
        self.verticalLayout_13.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_22 = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_22.sizePolicy().hasHeightForWidth())
        self.label_22.setSizePolicy(sizePolicy)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_10.addWidget(self.label_22)
        self.ml_param_tab = QtWidgets.QTableView(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ml_param_tab.sizePolicy().hasHeightForWidth())
        self.ml_param_tab.setSizePolicy(sizePolicy)
        self.ml_param_tab.setObjectName("ml_param_tab")
        self.verticalLayout_10.addWidget(self.ml_param_tab)
        self.horizontalLayout_4.addLayout(self.verticalLayout_10)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem)
        self.ml_tr_sv_btn = QtWidgets.QPushButton(self.tab)
        self.ml_tr_sv_btn.setMinimumSize(QtCore.QSize(0, 28))
        self.ml_tr_sv_btn.setObjectName("ml_tr_sv_btn")
        self.verticalLayout_11.addWidget(self.ml_tr_sv_btn)
        self.ml_tr_sd_btn = QtWidgets.QPushButton(self.tab)
        self.ml_tr_sd_btn.setObjectName("ml_tr_sd_btn")
        self.verticalLayout_11.addWidget(self.ml_tr_sd_btn)
        self.ml_tr_bg_btn = QtWidgets.QPushButton(self.tab)
        self.ml_tr_bg_btn.setMinimumSize(QtCore.QSize(0, 28))
        self.ml_tr_bg_btn.setMaximumSize(QtCore.QSize(16777215, 28))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Graphics/ml.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ml_tr_bg_btn.setIcon(icon)
        self.ml_tr_bg_btn.setIconSize(QtCore.QSize(56, 56))
        self.ml_tr_bg_btn.setFlat(False)
        self.ml_tr_bg_btn.setObjectName("ml_tr_bg_btn")
        self.verticalLayout_11.addWidget(self.ml_tr_bg_btn)
        self.horizontalLayout_4.addLayout(self.verticalLayout_11)
        self.horizontalLayout_4.setStretch(0, 3)
        self.horizontalLayout_4.setStretch(1, 1)
        self.verticalLayout_13.addLayout(self.horizontalLayout_4)
        self.verticalLayout_13.setStretch(0, 5)
        self.verticalLayout_13.setStretch(1, 1)
        self.gridLayout_10.addLayout(self.verticalLayout_13, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_63 = QtWidgets.QLabel(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_63.sizePolicy().hasHeightForWidth())
        self.label_63.setSizePolicy(sizePolicy)
        self.label_63.setObjectName("label_63")
        self.verticalLayout_6.addWidget(self.label_63)
        self.tr_el_tab_2 = QtWidgets.QTableView(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tr_el_tab_2.sizePolicy().hasHeightForWidth())
        self.tr_el_tab_2.setSizePolicy(sizePolicy)
        self.tr_el_tab_2.setObjectName("tr_el_tab_2")
        self.verticalLayout_6.addWidget(self.tr_el_tab_2)
        self.ml_op_bg_btn = QtWidgets.QPushButton(self.tab_2)
        self.ml_op_bg_btn.setMinimumSize(QtCore.QSize(0, 31))
        self.ml_op_bg_btn.setMaximumSize(QtCore.QSize(16777215, 31))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Graphics/opt.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ml_op_bg_btn.setIcon(icon1)
        self.ml_op_bg_btn.setIconSize(QtCore.QSize(56, 56))
        self.ml_op_bg_btn.setDefault(False)
        self.ml_op_bg_btn.setFlat(False)
        self.ml_op_bg_btn.setObjectName("ml_op_bg_btn")
        self.verticalLayout_6.addWidget(self.ml_op_bg_btn)
        self.gridLayout_3.addLayout(self.verticalLayout_6, 0, 1, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.ml_opt_fig_2 = QtWidgets.QGridLayout()
        self.ml_opt_fig_2.setSpacing(0)
        self.ml_opt_fig_2.setObjectName("ml_opt_fig_2")
        self.gridLayout_4.addLayout(self.ml_opt_fig_2, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_3, 1, 0, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.label_64 = QtWidgets.QLabel(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_64.sizePolicy().hasHeightForWidth())
        self.label_64.setSizePolicy(sizePolicy)
        self.label_64.setMaximumSize(QtCore.QSize(16777214, 31))
        self.label_64.setObjectName("label_64")
        self.verticalLayout_4.addWidget(self.label_64)
        self.hss_csc = QtWidgets.QComboBox(self.tab_2)
        self.hss_csc.setMinimumSize(QtCore.QSize(223, 31))
        self.hss_csc.setMaximumSize(QtCore.QSize(223, 31))
        self.hss_csc.setObjectName("hss_csc")
        self.verticalLayout_4.addWidget(self.hss_csc)
        self.label_8 = QtWidgets.QLabel(self.tab_2)
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 31))
        self.label_8.setObjectName("label_8")
        self.verticalLayout_4.addWidget(self.label_8)
        self.hss_fd = QtWidgets.QComboBox(self.tab_2)
        self.hss_fd.setMinimumSize(QtCore.QSize(223, 31))
        self.hss_fd.setMaximumSize(QtCore.QSize(223, 31))
        self.hss_fd.setObjectName("hss_fd")
        self.hss_fd.addItem("")
        self.hss_fd.addItem("")
        self.hss_fd.addItem("")
        self.hss_fd.addItem("")
        self.hss_fd.addItem("")
        self.verticalLayout_4.addWidget(self.hss_fd)
        self.hss_compute = QtWidgets.QPushButton(self.tab_2)
        self.hss_compute.setMinimumSize(QtCore.QSize(223, 31))
        self.hss_compute.setMaximumSize(QtCore.QSize(223, 31))
        self.hss_compute.setObjectName("hss_compute")
        self.verticalLayout_4.addWidget(self.hss_compute)
        self.gridLayout_3.addLayout(self.verticalLayout_4, 1, 1, 1, 1)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_6.sizePolicy().hasHeightForWidth())
        self.groupBox_6.setSizePolicy(sizePolicy)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_12.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_12.setVerticalSpacing(3)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.ml_opt_fig = QtWidgets.QGridLayout()
        self.ml_opt_fig.setSpacing(0)
        self.ml_opt_fig.setObjectName("ml_opt_fig")
        self.gridLayout_12.addLayout(self.ml_opt_fig, 0, 0, 1, 1)
        self.verticalLayout_9.addWidget(self.groupBox_6)
        self.gridLayout_13 = QtWidgets.QGridLayout()
        self.gridLayout_13.setHorizontalSpacing(7)
        self.gridLayout_13.setVerticalSpacing(0)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.label_57 = QtWidgets.QLabel(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_57.sizePolicy().hasHeightForWidth())
        self.label_57.setSizePolicy(sizePolicy)
        self.label_57.setMinimumSize(QtCore.QSize(0, 0))
        self.label_57.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_57.setObjectName("label_57")
        self.gridLayout_13.addWidget(self.label_57, 1, 1, 1, 1)
        self.ml_param_tab2 = QtWidgets.QTextBrowser(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ml_param_tab2.sizePolicy().hasHeightForWidth())
        self.ml_param_tab2.setSizePolicy(sizePolicy)
        self.ml_param_tab2.setMinimumSize(QtCore.QSize(200, 60))
        self.ml_param_tab2.setObjectName("ml_param_tab2")
        self.gridLayout_13.addWidget(self.ml_param_tab2, 2, 0, 1, 1)
        self.ml_opt_tab = QtWidgets.QTextBrowser(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ml_opt_tab.sizePolicy().hasHeightForWidth())
        self.ml_opt_tab.setSizePolicy(sizePolicy)
        self.ml_opt_tab.setMinimumSize(QtCore.QSize(0, 60))
        self.ml_opt_tab.setObjectName("ml_opt_tab")
        self.gridLayout_13.addWidget(self.ml_opt_tab, 2, 1, 1, 1)
        self.label_65 = QtWidgets.QLabel(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_65.sizePolicy().hasHeightForWidth())
        self.label_65.setSizePolicy(sizePolicy)
        self.label_65.setMinimumSize(QtCore.QSize(0, 0))
        self.label_65.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_65.setObjectName("label_65")
        self.gridLayout_13.addWidget(self.label_65, 1, 0, 1, 1)
        self.gridLayout_13.setColumnStretch(0, 1)
        self.verticalLayout_9.addLayout(self.gridLayout_13)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_24 = QtWidgets.QLabel(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_24.sizePolicy().hasHeightForWidth())
        self.label_24.setSizePolicy(sizePolicy)
        self.label_24.setMinimumSize(QtCore.QSize(0, 0))
        self.label_24.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_24.setObjectName("label_24")
        self.verticalLayout_8.addWidget(self.label_24)
        self.ml_param_tab_2 = QtWidgets.QTableView(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ml_param_tab_2.sizePolicy().hasHeightForWidth())
        self.ml_param_tab_2.setSizePolicy(sizePolicy)
        self.ml_param_tab_2.setObjectName("ml_param_tab_2")
        self.verticalLayout_8.addWidget(self.ml_param_tab_2)
        self.verticalLayout_9.addLayout(self.verticalLayout_8)
        self.verticalLayout_9.setStretch(0, 2)
        self.verticalLayout_9.setStretch(1, 1)
        self.verticalLayout_9.setStretch(2, 1)
        self.gridLayout_3.addLayout(self.verticalLayout_9, 0, 0, 1, 1)
        self.gridLayout_3.setColumnStretch(0, 3)
        self.gridLayout_3.setColumnStretch(1, 1)
        self.gridLayout_3.setRowStretch(0, 3)
        self.gridLayout_3.setRowStretch(1, 2)
        self.gridLayout_5.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tab_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_4.setCheckable(False)
        self.groupBox_4.setChecked(False)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.cv_f = QtWidgets.QComboBox(self.groupBox_4)
        self.cv_f.setObjectName("cv_f")
        self.cv_f.addItem("")
        self.cv_f.addItem("")
        self.cv_f.addItem("")
        self.cv_f.addItem("")
        self.cv_f.addItem("")
        self.gridLayout.addWidget(self.cv_f, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_4)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox_4)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.vd_tms = QtWidgets.QComboBox(self.groupBox_4)
        self.vd_tms.setObjectName("vd_tms")
        self.vd_tms.addItem("")
        self.vd_tms.addItem("")
        self.vd_tms.addItem("")
        self.vd_tms.addItem("")
        self.vd_tms.addItem("")
        self.vd_tms.addItem("")
        self.gridLayout.addWidget(self.vd_tms, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_4)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.cv_rand = QtWidgets.QLineEdit(self.groupBox_4)
        self.cv_rand.setObjectName("cv_rand")
        self.gridLayout.addWidget(self.cv_rand, 2, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.cv_sf = QtWidgets.QCheckBox(self.groupBox_4)
        self.cv_sf.setObjectName("cv_sf")
        self.verticalLayout_3.addWidget(self.cv_sf)
        self.verticalLayout_2.addWidget(self.groupBox_4)
        self.ml_sve_btn = QtWidgets.QPushButton(self.tab_3)
        self.ml_sve_btn.setObjectName("ml_sve_btn")
        self.verticalLayout_2.addWidget(self.ml_sve_btn)
        self.ml_el_btn = QtWidgets.QPushButton(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ml_el_btn.sizePolicy().hasHeightForWidth())
        self.ml_el_btn.setSizePolicy(sizePolicy)
        self.ml_el_btn.setMinimumSize(QtCore.QSize(0, 28))
        self.ml_el_btn.setMaximumSize(QtCore.QSize(16777215, 28))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Graphics/eval.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ml_el_btn.setIcon(icon2)
        self.ml_el_btn.setIconSize(QtCore.QSize(56, 56))
        self.ml_el_btn.setFlat(False)
        self.ml_el_btn.setObjectName("ml_el_btn")
        self.verticalLayout_2.addWidget(self.ml_el_btn)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_43 = QtWidgets.QVBoxLayout()
        self.verticalLayout_43.setSpacing(7)
        self.verticalLayout_43.setObjectName("verticalLayout_43")
        self.label_61 = QtWidgets.QLabel(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_61.sizePolicy().hasHeightForWidth())
        self.label_61.setSizePolicy(sizePolicy)
        self.label_61.setObjectName("label_61")
        self.verticalLayout_43.addWidget(self.label_61)
        self.ml_el_tab = QtWidgets.QTextBrowser(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ml_el_tab.sizePolicy().hasHeightForWidth())
        self.ml_el_tab.setSizePolicy(sizePolicy)
        self.ml_el_tab.setMinimumSize(QtCore.QSize(0, 0))
        self.ml_el_tab.setObjectName("ml_el_tab")
        self.verticalLayout_43.addWidget(self.ml_el_tab)
        self.horizontalLayout.addLayout(self.verticalLayout_43)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(1, 3)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.groupBox = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setVerticalSpacing(7)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.ml_el_fig = QtWidgets.QGridLayout()
        self.ml_el_fig.setSpacing(0)
        self.ml_el_fig.setObjectName("ml_el_fig")
        self.gridLayout_2.addLayout(self.ml_el_fig, 0, 0, 1, 1)
        self.verticalLayout_5.addWidget(self.groupBox)
        self.verticalLayout_5.setStretch(0, 2)
        self.verticalLayout_5.setStretch(1, 8)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.verticalLayout_44 = QtWidgets.QVBoxLayout()
        self.verticalLayout_44.setSpacing(7)
        self.verticalLayout_44.setObjectName("verticalLayout_44")
        self.label_55 = QtWidgets.QLabel(self.tab_3)
        self.label_55.setObjectName("label_55")
        self.verticalLayout_44.addWidget(self.label_55)
        self.tr_el_tab = QtWidgets.QTableView(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tr_el_tab.sizePolicy().hasHeightForWidth())
        self.tr_el_tab.setSizePolicy(sizePolicy)
        self.tr_el_tab.setObjectName("tr_el_tab")
        self.verticalLayout_44.addWidget(self.tr_el_tab)
        self.horizontalLayout_2.addLayout(self.verticalLayout_44)
        self.tabWidget.addTab(self.tab_3, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.infobox = QtWidgets.QLabel(WMML_train)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.infobox.setFont(font)
        self.infobox.setObjectName("infobox")
        self.verticalLayout.addWidget(self.infobox)

        self.retranslateUi(WMML_train)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(WMML_train)

    def retranslateUi(self, WMML_train):
        _translate = QtCore.QCoreApplication.translate
        WMML_train.setWindowTitle(_translate("WMML_train", "WMMLtrain"))
        self.label_6.setText(_translate("WMML_train", "Input Feature"))
        self.label_7.setText(_translate("WMML_train", "Target Variable"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("WMML_train", "Input Data"))
        self.groupBox_5.setTitle(_translate("WMML_train", "Training Comparison Chart"))
        self.label_20.setText(_translate("WMML_train", "Model Infomation"))
        self.label_60.setText(_translate("WMML_train", "Features"))
        self.label_44.setText(_translate("WMML_train", "Training Prediction"))
        self.label_22.setText(_translate("WMML_train", "Model Parameters"))
        self.ml_tr_sv_btn.setText(_translate("WMML_train", "Save Model"))
        self.ml_tr_sd_btn.setText(_translate("WMML_train", "Send Model"))
        self.ml_tr_bg_btn.setText(_translate("WMML_train", "Begin Training"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("WMML_train", "Train"))
        self.label_63.setText(_translate("WMML_train", "Record"))
        self.ml_op_bg_btn.setText(_translate("WMML_train", "Begin Optimization"))
        self.groupBox_3.setTitle(_translate("WMML_train", "Validation Curve"))
        self.label_64.setText(_translate("WMML_train", "Select Parameter"))
        self.label_8.setText(_translate("WMML_train", "Cross Validation Folds"))
        self.hss_fd.setItemText(0, _translate("WMML_train", "2"))
        self.hss_fd.setItemText(1, _translate("WMML_train", "3"))
        self.hss_fd.setItemText(2, _translate("WMML_train", "5"))
        self.hss_fd.setItemText(3, _translate("WMML_train", "10"))
        self.hss_fd.setItemText(4, _translate("WMML_train", "20"))
        self.hss_compute.setText(_translate("WMML_train", "Calculate Validation Curve"))
        self.groupBox_6.setTitle(_translate("WMML_train", "Optimization Record"))
        self.label_57.setText(_translate("WMML_train", "Optimization Index"))
        self.label_65.setText(_translate("WMML_train", "Parameter Info"))
        self.label_24.setText(_translate("WMML_train", "Optimizated Parameter"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("WMML_train", "Optimazation"))
        self.groupBox_4.setTitle(_translate("WMML_train", "Cross Validation Parameters"))
        self.cv_f.setItemText(0, _translate("WMML_train", "2"))
        self.cv_f.setItemText(1, _translate("WMML_train", "3"))
        self.cv_f.setItemText(2, _translate("WMML_train", "5"))
        self.cv_f.setItemText(3, _translate("WMML_train", "10"))
        self.cv_f.setItemText(4, _translate("WMML_train", "20"))
        self.label_4.setText(_translate("WMML_train", "Repeat Times"))
        self.label.setText(_translate("WMML_train", "Folds"))
        self.vd_tms.setItemText(0, _translate("WMML_train", "1"))
        self.vd_tms.setItemText(1, _translate("WMML_train", "2"))
        self.vd_tms.setItemText(2, _translate("WMML_train", "3"))
        self.vd_tms.setItemText(3, _translate("WMML_train", "5"))
        self.vd_tms.setItemText(4, _translate("WMML_train", "10"))
        self.vd_tms.setItemText(5, _translate("WMML_train", "20"))
        self.label_5.setText(_translate("WMML_train", "Random Seed"))
        self.cv_rand.setPlaceholderText(_translate("WMML_train", "None"))
        self.cv_sf.setText(_translate("WMML_train", "Shuffle Every Time"))
        self.ml_sve_btn.setText(_translate("WMML_train", "Save Validation Data"))
        self.ml_el_btn.setText(_translate("WMML_train", "Perform"))
        self.label_61.setText(_translate("WMML_train", "Validation Index"))
        self.groupBox.setTitle(_translate("WMML_train", "Cross Validation Comparison Chart"))
        self.label_55.setText(_translate("WMML_train", "Validation Prediction"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("WMML_train", "Test and Score"))
        self.infobox.setText(_translate("WMML_train", "....."))
