from PyQt5 import QtCore, QtGui, QtWidgets


# noinspection PyUnresolvedReferences
class Ui_WMML_csv(object):
    def setupUi(self, WMML_csv):
        WMML_csv.setObjectName("WMML_csv")
        WMML_csv.resize(730, 660)
        WMML_csv.setMinimumSize(QtCore.QSize(730, 660))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon/input_data.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        WMML_csv.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(WMML_csv)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.jzadfb = QtWidgets.QPushButton(WMML_csv)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.jzadfb.setFont(font)
        self.jzadfb.setObjectName("jzadfb")
        self.verticalLayout.addWidget(self.jzadfb)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.jzrmfb = QtWidgets.QPushButton(WMML_csv)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.jzrmfb.setFont(font)
        self.jzrmfb.setObjectName("jzrmfb")
        self.verticalLayout.addWidget(self.jzrmfb)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.jzstb = QtWidgets.QPushButton(WMML_csv)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.jzstb.setFont(font)
        self.jzstb.setObjectName("jzstb")
        self.verticalLayout.addWidget(self.jzstb)
        self.jzrmtgt = QtWidgets.QPushButton(WMML_csv)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.jzrmtgt.setFont(font)
        self.jzrmtgt.setObjectName("jzrmtgt")
        self.verticalLayout.addWidget(self.jzrmtgt)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.jzrld_btn = QtWidgets.QPushButton(WMML_csv)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.jzrld_btn.setFont(font)
        self.jzrld_btn.setObjectName("jzrld_btn")
        self.gridLayout_2.addWidget(self.jzrld_btn, 0, 0, 1, 1)
        self.jzatm_btn = QtWidgets.QPushButton(WMML_csv)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.jzatm_btn.setFont(font)
        self.jzatm_btn.setObjectName("jzatm_btn")
        self.gridLayout_2.addWidget(self.jzatm_btn, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.jzsdf = QtWidgets.QPushButton(WMML_csv)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.jzsdf.sizePolicy().hasHeightForWidth())
        self.jzsdf.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.jzsdf.setFont(font)
        self.jzsdf.setIconSize(QtCore.QSize(42, 42))
        self.jzsdf.setFlat(False)
        self.jzsdf.setObjectName("jzsdf")
        self.verticalLayout.addWidget(self.jzsdf)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_47 = QtWidgets.QLabel(WMML_csv)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_47.sizePolicy().hasHeightForWidth())
        self.label_47.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_47.setFont(font)
        self.label_47.setObjectName("label_47")
        self.verticalLayout_2.addWidget(self.label_47)
        self.jz_od_tab = QtWidgets.QTableView(WMML_csv)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.jz_od_tab.sizePolicy().hasHeightForWidth())
        self.jz_od_tab.setSizePolicy(sizePolicy)
        self.jz_od_tab.setSizeIncrement(QtCore.QSize(0, 20))
        self.jz_od_tab.setObjectName("jz_od_tab")
        self.verticalLayout_2.addWidget(self.jz_od_tab)
        self.verticalLayout_5.addLayout(self.verticalLayout_2)
        self.verticalLayout_5.setStretch(0, 1)
        self.horizontalLayout_3.addLayout(self.verticalLayout_5)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 8)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_5 = QtWidgets.QLabel(WMML_csv)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(0, 32))
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 32))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.jz_fd_tab = QtWidgets.QTableView(WMML_csv)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.jz_fd_tab.sizePolicy().hasHeightForWidth())
        self.jz_fd_tab.setSizePolicy(sizePolicy)
        self.jz_fd_tab.setSizeIncrement(QtCore.QSize(0, 20))
        self.jz_fd_tab.setObjectName("jz_fd_tab")
        self.verticalLayout_3.addWidget(self.jz_fd_tab)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_7 = QtWidgets.QLabel(WMML_csv)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMinimumSize(QtCore.QSize(0, 32))
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 32))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_4.addWidget(self.label_7)
        self.jz_td_tab = QtWidgets.QTableView(WMML_csv)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.jz_td_tab.sizePolicy().hasHeightForWidth())
        self.jz_td_tab.setSizePolicy(sizePolicy)
        self.jz_td_tab.setSizeIncrement(QtCore.QSize(0, 20))
        self.jz_td_tab.setObjectName("jz_td_tab")
        self.verticalLayout_4.addWidget(self.jz_td_tab)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.horizontalLayout_2.setStretch(0, 6)
        self.horizontalLayout_2.setStretch(1, 2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.verticalLayout_6.setStretch(0, 1)
        self.verticalLayout_6.setStretch(1, 3)
        self.gridLayout.addLayout(self.verticalLayout_6, 0, 0, 1, 1)
        self.infobox = QtWidgets.QLabel(WMML_csv)
        self.infobox.setObjectName("infobox")
        self.gridLayout.addWidget(self.infobox, 1, 0, 1, 1)

        self.retranslateUi(WMML_csv)
        QtCore.QMetaObject.connectSlotsByName(WMML_csv)

    def retranslateUi(self, WMML_csv):
        _translate = QtCore.QCoreApplication.translate
        WMML_csv.setWindowTitle(_translate("WMML_csv", "WMMLdata"))
        self.jzadfb.setText(_translate("WMML_csv", "Add Feature"))
        self.jzrmfb.setText(_translate("WMML_csv", "Remove Feature"))
        self.jzstb.setText(_translate("WMML_csv", "Set Target"))
        self.jzrmtgt.setText(_translate("WMML_csv", "Remove Target"))
        self.jzrld_btn.setText(_translate("WMML_csv", "Reload File"))
        self.jzatm_btn.setText(_translate("WMML_csv", "Auto Match"))
        self.jzsdf.setText(_translate("WMML_csv", "Send Data"))
        self.label_47.setText(_translate("WMML_csv", "Dataset"))
        self.label_5.setText(_translate("WMML_csv", "Selected Feature"))
        self.label_7.setText(_translate("WMML_csv", "Target Variable"))
        self.infobox.setText(_translate("WMML_csv", "....."))
