from PyQt5 import QtCore, QtGui, QtWidgets


# noinspection PyUnresolvedReferences
class Ui_WMML_correlation(object):
    def setupUi(self, WMML_correlation):
        WMML_correlation.setObjectName("WMML_correlation")
        WMML_correlation.resize(500, 500)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(WMML_correlation.sizePolicy().hasHeightForWidth())
        WMML_correlation.setSizePolicy(sizePolicy)
        WMML_correlation.setMinimumSize(QtCore.QSize(500, 500))
        self.gridLayout = QtWidgets.QGridLayout(WMML_correlation)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.idxsbx = QtWidgets.QComboBox(WMML_correlation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.idxsbx.sizePolicy().hasHeightForWidth())
        self.idxsbx.setSizePolicy(sizePolicy)
        self.idxsbx.setMinimumSize(QtCore.QSize(131, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.idxsbx.setFont(font)
        self.idxsbx.setObjectName("idxsbx")
        self.idxsbx.addItem("")
        self.idxsbx.addItem("")
        self.idxsbx.addItem("")
        self.idxsbx.addItem("")
        self.idxsbx.addItem("")
        self.idxsbx.addItem("")
        self.idxsbx.addItem("")
        self.idxsbx.addItem("")
        self.idxsbx.addItem("")
        self.idxsbx.addItem("")
        self.idxsbx.addItem("")
        self.idxsbx.addItem("")
        self.idxsbx.addItem("")
        self.horizontalLayout.addWidget(self.idxsbx)
        self.cptbtn = QtWidgets.QPushButton(WMML_correlation)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.cptbtn.setFont(font)
        self.cptbtn.setObjectName("cptbtn")
        self.horizontalLayout.addWidget(self.cptbtn)
        self.fe_s_corr_btn = QtWidgets.QPushButton(WMML_correlation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fe_s_corr_btn.sizePolicy().hasHeightForWidth())
        self.fe_s_corr_btn.setSizePolicy(sizePolicy)
        self.fe_s_corr_btn.setMinimumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.fe_s_corr_btn.setFont(font)
        self.fe_s_corr_btn.setIconSize(QtCore.QSize(28, 28))
        self.fe_s_corr_btn.setFlat(False)
        self.fe_s_corr_btn.setObjectName("fe_s_corr_btn")
        self.horizontalLayout.addWidget(self.fe_s_corr_btn)
        self.horizontalLayout.setStretch(0, 6)
        self.horizontalLayout.setStretch(1, 2)
        self.horizontalLayout.setStretch(2, 2)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(WMML_correlation)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.fe_corr_tab = QtWidgets.QTableView(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fe_corr_tab.sizePolicy().hasHeightForWidth())
        self.fe_corr_tab.setSizePolicy(sizePolicy)
        self.fe_corr_tab.setSizeIncrement(QtCore.QSize(0, 20))
        self.fe_corr_tab.setObjectName("fe_corr_tab")
        self.gridLayout_3.addWidget(self.fe_corr_tab, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.figgbx = QtWidgets.QGroupBox(self.tab_2)
        self.figgbx.setTitle("")
        self.figgbx.setObjectName("figgbx")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.figgbx)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.fe_corr_figview = QtWidgets.QGridLayout()
        self.fe_corr_figview.setObjectName("fe_corr_figview")
        self.gridLayout_4.addLayout(self.fe_corr_figview, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.figgbx, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.tabWidget, 1, 0, 1, 1)
        self.infobox = QtWidgets.QLabel(WMML_correlation)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.infobox.setFont(font)
        self.infobox.setObjectName("infobox")
        self.gridLayout.addWidget(self.infobox, 2, 0, 1, 1)

        self.retranslateUi(WMML_correlation)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(WMML_correlation)

    def retranslateUi(self, WMML_correlation):
        _translate = QtCore.QCoreApplication.translate
        WMML_correlation.setWindowTitle(_translate("WMML_correlation", "WMMLcorrelation"))
        self.idxsbx.setItemText(0, _translate("WMML_correlation", "Pearson correlation coefficient"))
        self.idxsbx.setItemText(1, _translate("WMML_correlation", "Pearson correlation coefficient-square root"))
        self.idxsbx.setItemText(2, _translate("WMML_correlation", "Maximal information coefficient"))
        self.idxsbx.setItemText(3, _translate("WMML_correlation", "Kendall\'s tau coefficient"))
        self.idxsbx.setItemText(4, _translate("WMML_correlation", "Spearman rank correlation"))
        self.idxsbx.setItemText(5, _translate("WMML_correlation", "Maximum asymmetry score"))
        self.idxsbx.setItemText(6, _translate("WMML_correlation", "Maximum edge value"))
        self.idxsbx.setItemText(7, _translate("WMML_correlation", "Minimum cell number"))
        self.idxsbx.setItemText(8, _translate("WMML_correlation", "Generalized mean information coefficient "))
        self.idxsbx.setItemText(9, _translate("WMML_correlation", "Total information coefficient"))
        self.idxsbx.setItemText(10, _translate("WMML_correlation", "Feature importance-by random forest"))
        self.idxsbx.setItemText(11, _translate("WMML_correlation", "Feature importance-by extra tree"))
        self.idxsbx.setItemText(12, _translate("WMML_correlation", "Linear regression coefficient"))
        self.cptbtn.setText(_translate("WMML_correlation", "Compute"))
        self.fe_s_corr_btn.setText(_translate("WMML_correlation", "Save Data"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("WMML_correlation", "Correlation Index"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("WMML_correlation", "Figure"))
        self.infobox.setText(_translate("WMML_correlation", "....."))
