from PyQt5 import QtCore, QtGui, QtWidgets


# noinspection PyUnresolvedReferences
class Ui_WMML_pca(object):
    def setupUi(self, WMML_pca):
        WMML_pca.setObjectName("WMML_pca")
        WMML_pca.resize(730, 668)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(WMML_pca.sizePolicy().hasHeightForWidth())
        WMML_pca.setSizePolicy(sizePolicy)
        WMML_pca.setMinimumSize(QtCore.QSize(500, 500))
        self.gridLayout = QtWidgets.QGridLayout(WMML_pca)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.jzcptfb = QtWidgets.QPushButton(WMML_pca)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.jzcptfb.setFont(font)
        self.jzcptfb.setObjectName("jzcptfb")
        self.horizontalLayout.addWidget(self.jzcptfb)
        self.jzsdf = QtWidgets.QPushButton(WMML_pca)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.jzsdf.sizePolicy().hasHeightForWidth())
        self.jzsdf.setSizePolicy(sizePolicy)
        self.jzsdf.setMinimumSize(QtCore.QSize(195, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.jzsdf.setFont(font)
        self.jzsdf.setIconSize(QtCore.QSize(42, 42))
        self.jzsdf.setFlat(False)
        self.jzsdf.setObjectName("jzsdf")
        self.horizontalLayout.addWidget(self.jzsdf)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(WMML_pca)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.data_tab = QtWidgets.QTableView(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data_tab.sizePolicy().hasHeightForWidth())
        self.data_tab.setSizePolicy(sizePolicy)
        self.data_tab.setSizeIncrement(QtCore.QSize(0, 20))
        self.data_tab.setObjectName("data_tab")
        self.gridLayout_3.addWidget(self.data_tab, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.figgbx = QtWidgets.QGroupBox(self.tab_2)
        self.figgbx.setTitle("")
        self.figgbx.setObjectName("figgbx")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.figgbx)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.pca_container = QtWidgets.QGridLayout()
        self.pca_container.setObjectName("pca_container")
        self.gridLayout_4.addLayout(self.pca_container, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.figgbx, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.data_tab_2 = QtWidgets.QTableView(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data_tab_2.sizePolicy().hasHeightForWidth())
        self.data_tab_2.setSizePolicy(sizePolicy)
        self.data_tab_2.setSizeIncrement(QtCore.QSize(0, 20))
        self.data_tab_2.setObjectName("data_tab_2")
        self.gridLayout_5.addWidget(self.data_tab_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.gridLayout.addWidget(self.tabWidget, 1, 0, 1, 1)
        self.infobox = QtWidgets.QLabel(WMML_pca)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.infobox.setFont(font)
        self.infobox.setObjectName("infobox")
        self.gridLayout.addWidget(self.infobox, 2, 0, 1, 1)

        self.retranslateUi(WMML_pca)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(WMML_pca)

    def retranslateUi(self, WMML_pca):
        _translate = QtCore.QCoreApplication.translate
        WMML_pca.setWindowTitle(_translate("WMML_pca", "WMMLpca"))
        self.jzcptfb.setText(_translate("WMML_pca", "Compute"))
        self.jzsdf.setText(_translate("WMML_pca", "Send Data"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("WMML_pca", "Input Data Table"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("WMML_pca", "PCA selection"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("WMML_pca", "Output Data Table"))
        self.infobox.setText(_translate("WMML_pca", "....."))
