from PyQt5 import QtCore, QtGui, QtWidgets


# noinspection PyUnresolvedReferences
class Ui_WMML_lr(object):
    def setupUi(self, WMML_lr):
        WMML_lr.setObjectName("WMML_lr")
        WMML_lr.resize(730, 660)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(WMML_lr.sizePolicy().hasHeightForWidth())
        WMML_lr.setSizePolicy(sizePolicy)
        WMML_lr.setMinimumSize(QtCore.QSize(730, 660))
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(WMML_lr)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tabWidget = QtWidgets.QTabWidget(WMML_lr)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.iptx = QtWidgets.QTableView(self.tab)
        self.iptx.setObjectName("iptx")
        self.gridLayout_2.addWidget(self.iptx, 1, 0, 1, 1)
        self.ipty = QtWidgets.QTableView(self.tab)
        self.ipty.setObjectName("ipty")
        self.gridLayout_2.addWidget(self.ipty, 1, 1, 1, 1)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_10.addWidget(self.label_9)
        self.id_lx = QtWidgets.QPushButton(self.tab)
        self.id_lx.setObjectName("id_lx")
        self.horizontalLayout_10.addWidget(self.id_lx)
        self.gridLayout_2.addLayout(self.horizontalLayout_10, 0, 0, 1, 1)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_10 = QtWidgets.QLabel(self.tab)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_11.addWidget(self.label_10)
        self.id_ly = QtWidgets.QPushButton(self.tab)
        self.id_ly.setObjectName("id_ly")
        self.horizontalLayout_11.addWidget(self.id_ly)
        self.gridLayout_2.addLayout(self.horizontalLayout_11, 0, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_8.addWidget(self.label_2)
        self.tp_fo = QtWidgets.QLabel(self.groupBox_3)
        self.tp_fo.setObjectName("tp_fo")
        self.horizontalLayout_8.addWidget(self.tp_fo)
        self.tp_odr = QtWidgets.QSlider(self.groupBox_3)
        self.tp_odr.setMinimum(1)
        self.tp_odr.setMaximum(10)
        self.tp_odr.setPageStep(1)
        self.tp_odr.setProperty("value", 3)
        self.tp_odr.setSliderPosition(3)
        self.tp_odr.setOrientation(QtCore.Qt.Horizontal)
        self.tp_odr.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.tp_odr.setObjectName("tp_odr")
        self.horizontalLayout_8.addWidget(self.tp_odr)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_9.addWidget(self.label_6)
        self.tp_opn = QtWidgets.QLineEdit(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tp_opn.sizePolicy().hasHeightForWidth())
        self.tp_opn.setSizePolicy(sizePolicy)
        self.tp_opn.setObjectName("tp_opn")
        self.horizontalLayout_9.addWidget(self.tp_opn)
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setObjectName("label")
        self.horizontalLayout_9.addWidget(self.label)
        self.tp_opt = QtWidgets.QComboBox(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tp_opt.sizePolicy().hasHeightForWidth())
        self.tp_opt.setSizePolicy(sizePolicy)
        self.tp_opt.setObjectName("tp_opt")
        self.tp_opt.addItem("")
        self.tp_opt.addItem("")
        self.tp_opt.addItem("")
        self.tp_opt.addItem("")
        self.horizontalLayout_9.addWidget(self.tp_opt)
        self.horizontalLayout_9.setStretch(0, 2)
        self.horizontalLayout_9.setStretch(1, 1)
        self.horizontalLayout_9.setStretch(2, 1)
        self.horizontalLayout_9.setStretch(3, 2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.gridLayout_5.addWidget(self.groupBox_3, 1, 0, 1, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_5.addItem(spacerItem)
        self.jzcpt = QtWidgets.QPushButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.jzcpt.sizePolicy().hasHeightForWidth())
        self.jzcpt.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.jzcpt.setFont(font)
        self.jzcpt.setIconSize(QtCore.QSize(42, 42))
        self.jzcpt.setFlat(False)
        self.jzcpt.setObjectName("jzcpt")
        self.verticalLayout_5.addWidget(self.jzcpt)
        self.jzsdf = QtWidgets.QPushButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.jzsdf.sizePolicy().hasHeightForWidth())
        self.jzsdf.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.jzsdf.setFont(font)
        self.jzsdf.setIconSize(QtCore.QSize(42, 42))
        self.jzsdf.setFlat(False)
        self.jzsdf.setObjectName("jzsdf")
        self.verticalLayout_5.addWidget(self.jzsdf)
        self.gridLayout_5.addLayout(self.verticalLayout_5, 1, 1, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.sm_lr = QtWidgets.QRadioButton(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.sm_lr.setFont(font)
        self.sm_lr.setChecked(True)
        self.sm_lr.setObjectName("sm_lr")
        self.gridLayout.addWidget(self.sm_lr, 0, 0, 1, 1)
        self.sm_lasso = QtWidgets.QRadioButton(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.sm_lasso.setFont(font)
        self.sm_lasso.setObjectName("sm_lasso")
        self.gridLayout.addWidget(self.sm_lasso, 0, 1, 1, 1)
        self.sm_enr = QtWidgets.QRadioButton(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.sm_enr.setFont(font)
        self.sm_enr.setObjectName("sm_enr")
        self.gridLayout.addWidget(self.sm_enr, 1, 0, 1, 1)
        self.sm_rr = QtWidgets.QRadioButton(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.sm_rr.setFont(font)
        self.sm_rr.setObjectName("sm_rr")
        self.gridLayout.addWidget(self.sm_rr, 1, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lr_fit = QtWidgets.QCheckBox(self.groupBox_4)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.lr_fit.setFont(font)
        self.lr_fit.setChecked(True)
        self.lr_fit.setObjectName("lr_fit")
        self.horizontalLayout_3.addWidget(self.lr_fit)
        self.horizontalLayout_7.addWidget(self.groupBox_4)
        self.groupBox_8 = QtWidgets.QGroupBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.groupBox_8.setFont(font)
        self.groupBox_8.setObjectName("groupBox_8")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_8)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.groupBox_8)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.lasso_alpha = QtWidgets.QLineEdit(self.groupBox_8)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.lasso_alpha.setFont(font)
        self.lasso_alpha.setObjectName("lasso_alpha")
        self.horizontalLayout_2.addWidget(self.lasso_alpha)
        self.lasso_fit = QtWidgets.QCheckBox(self.groupBox_8)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.lasso_fit.setFont(font)
        self.lasso_fit.setChecked(True)
        self.lasso_fit.setObjectName("lasso_fit")
        self.horizontalLayout_2.addWidget(self.lasso_fit)
        self.horizontalLayout_7.addWidget(self.groupBox_8)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.rr_fit = QtWidgets.QCheckBox(self.groupBox_5)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.rr_fit.setFont(font)
        self.rr_fit.setChecked(True)
        self.rr_fit.setObjectName("rr_fit")
        self.horizontalLayout_6.addWidget(self.rr_fit)
        self.groupBox_10 = QtWidgets.QGroupBox(self.groupBox_5)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.groupBox_10.setFont(font)
        self.groupBox_10.setObjectName("groupBox_10")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox_10)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.rr_gcv_auto = QtWidgets.QRadioButton(self.groupBox_10)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.rr_gcv_auto.setFont(font)
        self.rr_gcv_auto.setChecked(True)
        self.rr_gcv_auto.setObjectName("rr_gcv_auto")
        self.horizontalLayout_4.addWidget(self.rr_gcv_auto)
        self.rr_gcv_svd = QtWidgets.QRadioButton(self.groupBox_10)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.rr_gcv_svd.setFont(font)
        self.rr_gcv_svd.setObjectName("rr_gcv_svd")
        self.horizontalLayout_4.addWidget(self.rr_gcv_svd)
        self.rr_gcv_eigen = QtWidgets.QRadioButton(self.groupBox_10)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.rr_gcv_eigen.setFont(font)
        self.rr_gcv_eigen.setObjectName("rr_gcv_eigen")
        self.horizontalLayout_4.addWidget(self.rr_gcv_eigen)
        self.horizontalLayout_6.addWidget(self.groupBox_10)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.rr_cv = QtWidgets.QLineEdit(self.groupBox_5)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.rr_cv.setFont(font)
        self.rr_cv.setObjectName("rr_cv")
        self.horizontalLayout_5.addWidget(self.rr_cv)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.rr_alpha = QtWidgets.QLineEdit(self.groupBox_5)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.rr_alpha.setFont(font)
        self.rr_alpha.setObjectName("rr_alpha")
        self.horizontalLayout_5.addWidget(self.rr_alpha)
        self.horizontalLayout_5.setStretch(0, 1)
        self.horizontalLayout_5.setStretch(1, 1)
        self.horizontalLayout_5.setStretch(2, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.verticalLayout_2.addWidget(self.groupBox_5)
        self.groupBox_9 = QtWidgets.QGroupBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.groupBox_9.setFont(font)
        self.groupBox_9.setObjectName("groupBox_9")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_9)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_7 = QtWidgets.QLabel(self.groupBox_9)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout.addWidget(self.label_7)
        self.enr_alpha = QtWidgets.QLineEdit(self.groupBox_9)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.enr_alpha.setFont(font)
        self.enr_alpha.setObjectName("enr_alpha")
        self.horizontalLayout.addWidget(self.enr_alpha)
        self.label_8 = QtWidgets.QLabel(self.groupBox_9)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout.addWidget(self.label_8)
        self.enr_l1 = QtWidgets.QLineEdit(self.groupBox_9)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.enr_l1.setFont(font)
        self.enr_l1.setObjectName("enr_l1")
        self.horizontalLayout.addWidget(self.enr_l1)
        self.enr_fit = QtWidgets.QCheckBox(self.groupBox_9)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.enr_fit.setFont(font)
        self.enr_fit.setChecked(True)
        self.enr_fit.setObjectName("enr_fit")
        self.horizontalLayout.addWidget(self.enr_fit)
        self.verticalLayout_2.addWidget(self.groupBox_9)
        self.gridLayout_5.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.rmsev = QtWidgets.QTextBrowser(self.tab_2)
        self.rmsev.setObjectName("rmsev")
        self.gridLayout_5.addWidget(self.rmsev, 0, 1, 1, 1)
        self.horizontalLayout_15.addLayout(self.gridLayout_5)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.tab_3)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.optx = QtWidgets.QTableView(self.tab_3)
        self.optx.setObjectName("optx")
        self.gridLayout_4.addWidget(self.optx, 1, 0, 1, 1)
        self.opty = QtWidgets.QTableView(self.tab_3)
        self.opty.setObjectName("opty")
        self.gridLayout_4.addWidget(self.opty, 1, 1, 1, 1)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_12 = QtWidgets.QLabel(self.tab_3)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_12.addWidget(self.label_12)
        self.od_sx = QtWidgets.QPushButton(self.tab_3)
        self.od_sx.setObjectName("od_sx")
        self.horizontalLayout_12.addWidget(self.od_sx)
        self.gridLayout_4.addLayout(self.horizontalLayout_12, 0, 0, 1, 1)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_13 = QtWidgets.QLabel(self.tab_3)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_13.addWidget(self.label_13)
        self.od_syy = QtWidgets.QPushButton(self.tab_3)
        self.od_syy.setObjectName("od_syy")
        self.horizontalLayout_13.addWidget(self.od_syy)
        self.gridLayout_4.addLayout(self.horizontalLayout_13, 0, 1, 1, 1)
        self.horizontalLayout_14.addLayout(self.gridLayout_4)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.opids = QtWidgets.QTableView(self.tab_4)
        self.opids.setObjectName("opids")
        self.gridLayout_6.addWidget(self.opids, 1, 0, 1, 1)
        self.opcofxy = QtWidgets.QTableView(self.tab_4)
        self.opcofxy.setObjectName("opcofxy")
        self.gridLayout_6.addWidget(self.opcofxy, 1, 1, 1, 1)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_14 = QtWidgets.QLabel(self.tab_4)
        self.label_14.setMinimumSize(QtCore.QSize(0, 28))
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_16.addWidget(self.label_14)
        self.gridLayout_6.addLayout(self.horizontalLayout_16, 0, 0, 1, 1)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_15 = QtWidgets.QLabel(self.tab_4)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_17.addWidget(self.label_15)
        self.gridLayout_6.addLayout(self.horizontalLayout_17, 0, 1, 1, 1)
        self.gridLayout_6.setColumnStretch(0, 1)
        self.gridLayout_6.setColumnStretch(1, 4)
        self.gridLayout_7.addLayout(self.gridLayout_6, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_4, "")
        self.verticalLayout_4.addWidget(self.tabWidget)
        self.infobox = QtWidgets.QLabel(WMML_lr)
        self.infobox.setObjectName("infobox")
        self.verticalLayout_4.addWidget(self.infobox)

        self.retranslateUi(WMML_lr)
        self.tabWidget.setCurrentIndex(0)
        self.sm_lr.clicked['bool'].connect(self.groupBox_4.setEnabled)
        self.sm_lr.clicked['bool'].connect(self.groupBox_8.setDisabled)
        self.sm_lr.clicked['bool'].connect(self.groupBox_5.setDisabled)
        self.sm_lr.clicked['bool'].connect(self.groupBox_9.setDisabled)
        self.sm_lasso.clicked['bool'].connect(self.groupBox_4.setDisabled)
        self.sm_lasso.clicked['bool'].connect(self.groupBox_8.setEnabled)
        self.sm_lasso.clicked['bool'].connect(self.groupBox_5.setDisabled)
        self.sm_lasso.clicked['bool'].connect(self.groupBox_9.setDisabled)
        self.sm_enr.clicked['bool'].connect(self.groupBox_4.setDisabled)
        self.sm_enr.clicked['bool'].connect(self.groupBox_8.setDisabled)
        self.sm_enr.clicked['bool'].connect(self.groupBox_5.setDisabled)
        self.sm_enr.clicked['bool'].connect(self.groupBox_9.setEnabled)
        self.sm_rr.clicked['bool'].connect(self.groupBox_4.setDisabled)
        self.sm_rr.clicked['bool'].connect(self.groupBox_8.setDisabled)
        self.sm_rr.clicked['bool'].connect(self.groupBox_5.setEnabled)
        self.sm_rr.clicked['bool'].connect(self.groupBox_9.setDisabled)
        QtCore.QMetaObject.connectSlotsByName(WMML_lr)

    def retranslateUi(self, WMML_lr):
        _translate = QtCore.QCoreApplication.translate
        WMML_lr.setWindowTitle(_translate("WMML_lr", "WMMLlr"))
        self.label_9.setText(_translate("WMML_lr", "Input X"))
        self.id_lx.setText(_translate("WMML_lr", "Load X"))
        self.label_10.setText(_translate("WMML_lr", "Input Y"))
        self.id_ly.setText(_translate("WMML_lr", "Load Y"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("WMML_lr", "Input Data"))
        self.groupBox_3.setTitle(_translate("WMML_lr", "Transformation Parameters"))
        self.label_2.setText(_translate("WMML_lr", "Fitting Order:"))
        self.tp_fo.setText(_translate("WMML_lr", "3"))
        self.label_6.setText(_translate("WMML_lr", "Output Data Number"))
        self.tp_opn.setText(_translate("WMML_lr", "None"))
        self.tp_opn.setPlaceholderText(_translate("WMML_lr", "None"))
        self.label.setText(_translate("WMML_lr", "Output Types"))
        self.tp_opt.setItemText(0, _translate("WMML_lr", "Uniform Linear"))
        self.tp_opt.setItemText(1, _translate("WMML_lr", "Log2"))
        self.tp_opt.setItemText(2, _translate("WMML_lr", "Log10"))
        self.tp_opt.setItemText(3, _translate("WMML_lr", "Ln"))
        self.jzcpt.setText(_translate("WMML_lr", "Compute"))
        self.jzsdf.setText(_translate("WMML_lr", "Send Model"))
        self.groupBox_2.setTitle(_translate("WMML_lr", "Model Parameters"))
        self.groupBox.setTitle(_translate("WMML_lr", "Select Model"))
        self.sm_lr.setText(_translate("WMML_lr", "Linear Regression"))
        self.sm_lasso.setText(_translate("WMML_lr", "LASSO"))
        self.sm_enr.setText(_translate("WMML_lr", "Elastic Net"))
        self.sm_rr.setText(_translate("WMML_lr", "Ridge Regression"))
        self.groupBox_4.setTitle(_translate("WMML_lr", "Linear Regression"))
        self.lr_fit.setText(_translate("WMML_lr", "Fit Intercept"))
        self.groupBox_8.setTitle(_translate("WMML_lr", "LASSO"))
        self.label_4.setText(_translate("WMML_lr", "α"))
        self.lasso_alpha.setText(_translate("WMML_lr", "1.0"))
        self.lasso_alpha.setPlaceholderText(_translate("WMML_lr", "0"))
        self.lasso_fit.setText(_translate("WMML_lr", "Fit Intercept"))
        self.groupBox_5.setTitle(_translate("WMML_lr", "Ridge Regression"))
        self.rr_fit.setText(_translate("WMML_lr", "Fit Intercept"))
        self.groupBox_10.setTitle(_translate("WMML_lr", "Leave One Out Validation Mode"))
        self.rr_gcv_auto.setText(_translate("WMML_lr", "Auto"))
        self.rr_gcv_svd.setText(_translate("WMML_lr", "SVD"))
        self.rr_gcv_eigen.setText(_translate("WMML_lr", "Eigen Value"))
        self.label_3.setText(_translate("WMML_lr", "Cross Validation Folds"))
        self.rr_cv.setText(_translate("WMML_lr", "None"))
        self.rr_cv.setPlaceholderText(_translate("WMML_lr", "None"))
        self.label_5.setText(_translate("WMML_lr", "α"))
        self.rr_alpha.setText(_translate("WMML_lr", "auto"))
        self.rr_alpha.setPlaceholderText(_translate("WMML_lr", "auto"))
        self.groupBox_9.setTitle(_translate("WMML_lr", "Elastic Net"))
        self.label_7.setText(_translate("WMML_lr", "α"))
        self.enr_alpha.setText(_translate("WMML_lr", "1.0"))
        self.enr_alpha.setPlaceholderText(_translate("WMML_lr", "0"))
        self.label_8.setText(_translate("WMML_lr", "L1 ratio"))
        self.enr_l1.setText(_translate("WMML_lr", "0.5"))
        self.enr_l1.setPlaceholderText(_translate("WMML_lr", "0~1"))
        self.enr_fit.setText(_translate("WMML_lr", "Fit Intercept"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("WMML_lr", "Transformation Selection"))
        self.label_12.setText(_translate("WMML_lr", "Output X"))
        self.od_sx.setText(_translate("WMML_lr", "Save X"))
        self.label_13.setText(_translate("WMML_lr", "Output Y"))
        self.od_syy.setText(_translate("WMML_lr", "Save Y"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("WMML_lr", "Output Data"))
        self.label_14.setText(_translate("WMML_lr", "Indices"))
        self.label_15.setText(_translate("WMML_lr", "Coefficient"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("WMML_lr", "Fitted Coefficient"))
        self.infobox.setText(_translate("WMML_lr", "....."))
