from PyQt5 import QtCore, QtGui, QtWidgets


# noinspection PyUnresolvedReferences
class Ui_WMML_gbdt(object):
    def setupUi(self, WMML_gbdt):
        WMML_gbdt.setObjectName("WMML_gbdt")
        WMML_gbdt.resize(1091, 729)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(WMML_gbdt.sizePolicy().hasHeightForWidth())
        WMML_gbdt.setSizePolicy(sizePolicy)
        WMML_gbdt.setMinimumSize(QtCore.QSize(1091, 729))
        self.gridLayout_12 = QtWidgets.QGridLayout(WMML_gbdt)
        self.gridLayout_12.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox = QtWidgets.QGroupBox(WMML_gbdt)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(561, 601))
        self.groupBox.setMaximumSize(QtCore.QSize(561, 601))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.ps_msl = QtWidgets.QLineEdit(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.ps_msl.setFont(font)
        self.ps_msl.setObjectName("ps_msl")
        self.gridLayout_8.addWidget(self.ps_msl, 5, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox)
        self.label_14.setObjectName("label_14")
        self.gridLayout_8.addWidget(self.label_14, 0, 0, 1, 1)
        self.ps_mss = QtWidgets.QLineEdit(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.ps_mss.setFont(font)
        self.ps_mss.setObjectName("ps_mss")
        self.gridLayout_8.addWidget(self.ps_mss, 4, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.gridLayout_8.addWidget(self.label_22, 7, 0, 1, 1)
        self.ps_ss = QtWidgets.QLineEdit(self.groupBox)
        self.ps_ss.setObjectName("ps_ss")
        self.gridLayout_8.addWidget(self.ps_ss, 1, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_8.addWidget(self.label_6, 6, 0, 1, 1)
        self.ps_est = QtWidgets.QLineEdit(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.ps_est.setFont(font)
        self.ps_est.setObjectName("ps_est")
        self.gridLayout_8.addWidget(self.ps_est, 2, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_8.addWidget(self.label_5, 5, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.gridLayout_8.addWidget(self.label_21, 8, 0, 1, 1)
        self.ps_lr = QtWidgets.QLineEdit(self.groupBox)
        self.ps_lr.setObjectName("ps_lr")
        self.gridLayout_8.addWidget(self.ps_lr, 0, 1, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.groupBox)
        self.label_31.setObjectName("label_31")
        self.gridLayout_8.addWidget(self.label_31, 1, 0, 1, 1)
        self.ps_md = QtWidgets.QLineEdit(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.ps_md.setFont(font)
        self.ps_md.setObjectName("ps_md")
        self.gridLayout_8.addWidget(self.ps_md, 3, 1, 1, 1)
        self.ps_mid = QtWidgets.QLineEdit(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.ps_mid.setFont(font)
        self.ps_mid.setObjectName("ps_mid")
        self.gridLayout_8.addWidget(self.ps_mid, 8, 1, 1, 1)
        self.ps_mln = QtWidgets.QLineEdit(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.ps_mln.setFont(font)
        self.ps_mln.setObjectName("ps_mln")
        self.gridLayout_8.addWidget(self.ps_mln, 7, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_8.addWidget(self.label_4, 4, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_8.addWidget(self.label_3, 3, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_8.addWidget(self.label_2, 2, 0, 1, 1)
        self.ps_mwfl = QtWidgets.QLineEdit(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.ps_mwfl.setFont(font)
        self.ps_mwfl.setObjectName("ps_mwfl")
        self.gridLayout_8.addWidget(self.ps_mwfl, 6, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.groupBox)
        self.label_15.setObjectName("label_15")
        self.gridLayout_8.addWidget(self.label_15, 9, 0, 1, 1)
        self.ps_rand = QtWidgets.QLineEdit(self.groupBox)
        self.ps_rand.setObjectName("ps_rand")
        self.gridLayout_8.addWidget(self.ps_rand, 9, 1, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_8)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.groupBox_8 = QtWidgets.QGroupBox(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.groupBox_8.setFont(font)
        self.groupBox_8.setCheckable(False)
        self.groupBox_8.setChecked(False)
        self.groupBox_8.setObjectName("groupBox_8")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_8)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.ps_l_sqr = QtWidgets.QRadioButton(self.groupBox_8)
        self.ps_l_sqr.setChecked(True)
        self.ps_l_sqr.setObjectName("ps_l_sqr")
        self.gridLayout_3.addWidget(self.ps_l_sqr, 0, 0, 1, 1)
        self.ps_l_hub = QtWidgets.QRadioButton(self.groupBox_8)
        self.ps_l_hub.setObjectName("ps_l_hub")
        self.gridLayout_3.addWidget(self.ps_l_hub, 0, 1, 1, 1)
        self.ps_l_abr = QtWidgets.QRadioButton(self.groupBox_8)
        self.ps_l_abr.setObjectName("ps_l_abr")
        self.gridLayout_3.addWidget(self.ps_l_abr, 1, 1, 1, 1)
        self.ps_l_quat = QtWidgets.QRadioButton(self.groupBox_8)
        self.ps_l_quat.setObjectName("ps_l_quat")
        self.gridLayout_3.addWidget(self.ps_l_quat, 1, 0, 1, 1)
        self.verticalLayout_5.addWidget(self.groupBox_8)
        self.groupBox_9 = QtWidgets.QGroupBox(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.groupBox_9.setFont(font)
        self.groupBox_9.setCheckable(False)
        self.groupBox_9.setChecked(False)
        self.groupBox_9.setObjectName("groupBox_9")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_9)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.ps_c_f = QtWidgets.QRadioButton(self.groupBox_9)
        self.ps_c_f.setChecked(True)
        self.ps_c_f.setObjectName("ps_c_f")
        self.gridLayout_5.addWidget(self.ps_c_f, 0, 0, 1, 1)
        self.ps_c_mse = QtWidgets.QRadioButton(self.groupBox_9)
        self.ps_c_mse.setObjectName("ps_c_mse")
        self.gridLayout_5.addWidget(self.ps_c_mse, 0, 1, 1, 1)
        self.ps_c_sqr = QtWidgets.QRadioButton(self.groupBox_9)
        self.ps_c_sqr.setObjectName("ps_c_sqr")
        self.gridLayout_5.addWidget(self.ps_c_sqr, 1, 1, 1, 1)
        self.ps_c_mae = QtWidgets.QRadioButton(self.groupBox_9)
        self.ps_c_mae.setObjectName("ps_c_mae")
        self.gridLayout_5.addWidget(self.ps_c_mae, 1, 0, 1, 1)
        self.verticalLayout_5.addWidget(self.groupBox_9)
        self.groupBox_10 = QtWidgets.QGroupBox(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.groupBox_10.setFont(font)
        self.groupBox_10.setCheckable(False)
        self.groupBox_10.setChecked(False)
        self.groupBox_10.setObjectName("groupBox_10")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_10)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.ps_mf_n = QtWidgets.QRadioButton(self.groupBox_10)
        self.ps_mf_n.setChecked(True)
        self.ps_mf_n.setObjectName("ps_mf_n")
        self.gridLayout_6.addWidget(self.ps_mf_n, 0, 0, 1, 1)
        self.ps_mf_auto = QtWidgets.QRadioButton(self.groupBox_10)
        self.ps_mf_auto.setObjectName("ps_mf_auto")
        self.gridLayout_6.addWidget(self.ps_mf_auto, 1, 0, 1, 1)
        self.ps_mf_log2 = QtWidgets.QRadioButton(self.groupBox_10)
        self.ps_mf_log2.setObjectName("ps_mf_log2")
        self.gridLayout_6.addWidget(self.ps_mf_log2, 1, 1, 1, 1)
        self.ps_mf_sqr = QtWidgets.QRadioButton(self.groupBox_10)
        self.ps_mf_sqr.setObjectName("ps_mf_sqr")
        self.gridLayout_6.addWidget(self.ps_mf_sqr, 0, 1, 1, 1)
        self.verticalLayout_5.addWidget(self.groupBox_10)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_24 = QtWidgets.QLabel(self.groupBox)
        self.label_24.setObjectName("label_24")
        self.gridLayout_7.addWidget(self.label_24, 1, 0, 1, 1)
        self.ps_tol = QtWidgets.QLineEdit(self.groupBox)
        self.ps_tol.setObjectName("ps_tol")
        self.gridLayout_7.addWidget(self.ps_tol, 1, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.groupBox)
        self.label_18.setObjectName("label_18")
        self.gridLayout_7.addWidget(self.label_18, 0, 0, 1, 1)
        self.ps_alpha = QtWidgets.QLineEdit(self.groupBox)
        self.ps_alpha.setObjectName("ps_alpha")
        self.gridLayout_7.addWidget(self.ps_alpha, 0, 1, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_7)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 1)
        self.verticalLayout_9.addLayout(self.horizontalLayout)
        self.groupBox_12 = QtWidgets.QGroupBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_12.sizePolicy().hasHeightForWidth())
        self.groupBox_12.setSizePolicy(sizePolicy)
        self.groupBox_12.setMinimumSize(QtCore.QSize(537, 201))
        self.groupBox_12.setObjectName("groupBox_12")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_12)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.f_load = QtWidgets.QPushButton(self.groupBox_12)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Graphics/loadspace.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.f_load.setIcon(icon)
        self.f_load.setIconSize(QtCore.QSize(40, 40))
        self.f_load.setFlat(False)
        self.f_load.setObjectName("f_load")
        self.verticalLayout_6.addWidget(self.f_load)
        self.addButton_2 = QtWidgets.QPushButton(self.groupBox_12)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Graphics/rand.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addButton_2.setIcon(icon1)
        self.addButton_2.setIconSize(QtCore.QSize(40, 40))
        self.addButton_2.setFlat(False)
        self.addButton_2.setObjectName("addButton_2")
        self.verticalLayout_6.addWidget(self.addButton_2)
        self.addButton_3 = QtWidgets.QPushButton(self.groupBox_12)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Graphics/zoomout.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addButton_3.setIcon(icon2)
        self.addButton_3.setIconSize(QtCore.QSize(24, 24))
        self.addButton_3.setFlat(False)
        self.addButton_3.setObjectName("addButton_3")
        self.verticalLayout_6.addWidget(self.addButton_3)
        self.verticalLayout_6.setStretch(0, 1)
        self.verticalLayout_6.setStretch(1, 1)
        self.verticalLayout_6.setStretch(2, 1)
        self.horizontalLayout_2.addLayout(self.verticalLayout_6)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_27 = QtWidgets.QLabel(self.groupBox_12)
        self.label_27.setObjectName("label_27")
        self.gridLayout.addWidget(self.label_27, 0, 1, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.groupBox_12)
        self.label_26.setObjectName("label_26")
        self.gridLayout.addWidget(self.label_26, 0, 0, 1, 1)
        self.f_load_info = QtWidgets.QTextBrowser(self.groupBox_12)
        self.f_load_info.setObjectName("f_load_info")
        self.gridLayout.addWidget(self.f_load_info, 1, 0, 1, 1)
        self.f_load_f1 = QtWidgets.QTextBrowser(self.groupBox_12)
        self.f_load_f1.setObjectName("f_load_f1")
        self.gridLayout.addWidget(self.f_load_f1, 1, 1, 1, 1)
        self.verticalLayout_8.addLayout(self.gridLayout)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_28 = QtWidgets.QLabel(self.groupBox_12)
        self.label_28.setObjectName("label_28")
        self.verticalLayout_7.addWidget(self.label_28)
        self.f_load_f1_2 = QtWidgets.QTextBrowser(self.groupBox_12)
        self.f_load_f1_2.setObjectName("f_load_f1_2")
        self.verticalLayout_7.addWidget(self.f_load_f1_2)
        self.verticalLayout_8.addLayout(self.verticalLayout_7)
        self.horizontalLayout_2.addLayout(self.verticalLayout_8)
        self.verticalLayout_9.addWidget(self.groupBox_12)
        self.verticalLayout_3.addWidget(self.groupBox)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.jzsdf = QtWidgets.QPushButton(WMML_gbdt)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.jzsdf.setFont(font)
        self.jzsdf.setObjectName("jzsdf")
        self.verticalLayout_3.addWidget(self.jzsdf)
        self.infobox = QtWidgets.QLabel(WMML_gbdt)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.infobox.setFont(font)
        self.infobox.setObjectName("infobox")
        self.verticalLayout_3.addWidget(self.infobox)
        self.gridLayout_12.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(WMML_gbdt)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(501, 707))
        self.groupBox_2.setMaximumSize(QtCore.QSize(501, 707))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.groupBox_2.setFont(font)
        self.groupBox_2.setCheckable(True)
        self.groupBox_2.setChecked(False)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_11 = QtWidgets.QGroupBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_11.sizePolicy().hasHeightForWidth())
        self.groupBox_11.setSizePolicy(sizePolicy)
        self.groupBox_11.setMinimumSize(QtCore.QSize(471, 556))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.groupBox_11.setFont(font)
        self.groupBox_11.setObjectName("groupBox_11")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_11)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.hss_mss_max = QtWidgets.QLineEdit(self.groupBox_11)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.hss_mss_max.setFont(font)
        self.hss_mss_max.setObjectName("hss_mss_max")
        self.gridLayout_2.addWidget(self.hss_mss_max, 5, 2, 1, 1)
        self.hss_alpha_min = QtWidgets.QLineEdit(self.groupBox_11)
        self.hss_alpha_min.setObjectName("hss_alpha_min")
        self.gridLayout_2.addWidget(self.hss_alpha_min, 10, 1, 1, 1)
        self.hss_msl_min = QtWidgets.QLineEdit(self.groupBox_11)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.hss_msl_min.setFont(font)
        self.hss_msl_min.setObjectName("hss_msl_min")
        self.gridLayout_2.addWidget(self.hss_msl_min, 6, 1, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.groupBox_11)
        self.label_32.setObjectName("label_32")
        self.gridLayout_2.addWidget(self.label_32, 2, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox_11)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 7, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox_11)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 5, 0, 1, 1)
        self.hss_alpha_max = QtWidgets.QLineEdit(self.groupBox_11)
        self.hss_alpha_max.setObjectName("hss_alpha_max")
        self.gridLayout_2.addWidget(self.hss_alpha_max, 10, 2, 1, 1)
        self.hss_md_max = QtWidgets.QLineEdit(self.groupBox_11)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.hss_md_max.setFont(font)
        self.hss_md_max.setObjectName("hss_md_max")
        self.gridLayout_2.addWidget(self.hss_md_max, 4, 2, 1, 1)
        self.hss_mwfl_min = QtWidgets.QLineEdit(self.groupBox_11)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.hss_mwfl_min.setFont(font)
        self.hss_mwfl_min.setObjectName("hss_mwfl_min")
        self.gridLayout_2.addWidget(self.hss_mwfl_min, 7, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.groupBox_11)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.gridLayout_2.addWidget(self.label_19, 8, 0, 1, 1)
        self.hss_mss_min = QtWidgets.QLineEdit(self.groupBox_11)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.hss_mss_min.setFont(font)
        self.hss_mss_min.setObjectName("hss_mss_min")
        self.gridLayout_2.addWidget(self.hss_mss_min, 5, 1, 1, 1)
        self.hss_mid_max = QtWidgets.QLineEdit(self.groupBox_11)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.hss_mid_max.setFont(font)
        self.hss_mid_max.setObjectName("hss_mid_max")
        self.gridLayout_2.addWidget(self.hss_mid_max, 9, 2, 1, 1)
        self.hss_mln_min = QtWidgets.QLineEdit(self.groupBox_11)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.hss_mln_min.setFont(font)
        self.hss_mln_min.setObjectName("hss_mln_min")
        self.gridLayout_2.addWidget(self.hss_mln_min, 8, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_11)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 6, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.groupBox_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.gridLayout_2.addWidget(self.label_16, 0, 1, 1, 1)
        self.hss_est_max = QtWidgets.QLineEdit(self.groupBox_11)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.hss_est_max.setFont(font)
        self.hss_est_max.setObjectName("hss_est_max")
        self.gridLayout_2.addWidget(self.hss_est_max, 3, 2, 1, 1)
        self.hss_mid_min = QtWidgets.QLineEdit(self.groupBox_11)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.hss_mid_min.setFont(font)
        self.hss_mid_min.setObjectName("hss_mid_min")
        self.gridLayout_2.addWidget(self.hss_mid_min, 9, 1, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.groupBox_11)
        self.label_35.setObjectName("label_35")
        self.gridLayout_2.addWidget(self.label_35, 10, 0, 1, 1)
        self.hss_mwfl_max = QtWidgets.QLineEdit(self.groupBox_11)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.hss_mwfl_max.setFont(font)
        self.hss_mwfl_max.setObjectName("hss_mwfl_max")
        self.gridLayout_2.addWidget(self.hss_mwfl_max, 7, 2, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.groupBox_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.gridLayout_2.addWidget(self.label_17, 0, 2, 1, 1)
        self.hss_ss_max = QtWidgets.QLineEdit(self.groupBox_11)
        self.hss_ss_max.setObjectName("hss_ss_max")
        self.gridLayout_2.addWidget(self.hss_ss_max, 2, 2, 1, 1)
        self.hss_msl_max = QtWidgets.QLineEdit(self.groupBox_11)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.hss_msl_max.setFont(font)
        self.hss_msl_max.setObjectName("hss_msl_max")
        self.gridLayout_2.addWidget(self.hss_msl_max, 6, 2, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.groupBox_11)
        self.label_30.setObjectName("label_30")
        self.gridLayout_2.addWidget(self.label_30, 1, 0, 1, 1)
        self.hss_mln_max = QtWidgets.QLineEdit(self.groupBox_11)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.hss_mln_max.setFont(font)
        self.hss_mln_max.setObjectName("hss_mln_max")
        self.gridLayout_2.addWidget(self.hss_mln_max, 8, 2, 1, 1)
        self.hss_lr_max = QtWidgets.QLineEdit(self.groupBox_11)
        self.hss_lr_max.setObjectName("hss_lr_max")
        self.gridLayout_2.addWidget(self.hss_lr_max, 1, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_11)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 4, 0, 1, 1)
        self.hss_lr_min = QtWidgets.QLineEdit(self.groupBox_11)
        self.hss_lr_min.setObjectName("hss_lr_min")
        self.gridLayout_2.addWidget(self.hss_lr_min, 1, 1, 1, 1)
        self.hss_ss_min = QtWidgets.QLineEdit(self.groupBox_11)
        self.hss_ss_min.setObjectName("hss_ss_min")
        self.gridLayout_2.addWidget(self.hss_ss_min, 2, 1, 1, 1)
        self.hss_md_min = QtWidgets.QLineEdit(self.groupBox_11)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.hss_md_min.setFont(font)
        self.hss_md_min.setObjectName("hss_md_min")
        self.gridLayout_2.addWidget(self.hss_md_min, 4, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_11)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 3, 0, 1, 1)
        self.hss_est_min = QtWidgets.QLineEdit(self.groupBox_11)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.hss_est_min.setFont(font)
        self.hss_est_min.setObjectName("hss_est_min")
        self.gridLayout_2.addWidget(self.hss_est_min, 3, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.groupBox_11)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.gridLayout_2.addWidget(self.label_20, 9, 0, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.groupBox_11)
        self.label_33.setObjectName("label_33")
        self.gridLayout_2.addWidget(self.label_33, 11, 0, 1, 1)
        self.hss_tol_min = QtWidgets.QLineEdit(self.groupBox_11)
        self.hss_tol_min.setObjectName("hss_tol_min")
        self.gridLayout_2.addWidget(self.hss_tol_min, 11, 1, 1, 1)
        self.hss_tol_max = QtWidgets.QLineEdit(self.groupBox_11)
        self.hss_tol_max.setObjectName("hss_tol_max")
        self.gridLayout_2.addWidget(self.hss_tol_max, 11, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.groupBox_13 = QtWidgets.QGroupBox(self.groupBox_11)
        self.groupBox_13.setCheckable(False)
        self.groupBox_13.setChecked(False)
        self.groupBox_13.setObjectName("groupBox_13")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox_13)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.hss_l_quat = QtWidgets.QCheckBox(self.groupBox_13)
        self.hss_l_quat.setChecked(True)
        self.hss_l_quat.setObjectName("hss_l_quat")
        self.gridLayout_9.addWidget(self.hss_l_quat, 1, 0, 1, 1)
        self.hss_l_sqr = QtWidgets.QCheckBox(self.groupBox_13)
        self.hss_l_sqr.setChecked(True)
        self.hss_l_sqr.setObjectName("hss_l_sqr")
        self.gridLayout_9.addWidget(self.hss_l_sqr, 0, 0, 1, 1)
        self.hss_l_hub = QtWidgets.QCheckBox(self.groupBox_13)
        self.hss_l_hub.setChecked(True)
        self.hss_l_hub.setObjectName("hss_l_hub")
        self.gridLayout_9.addWidget(self.hss_l_hub, 2, 0, 1, 1)
        self.hss_l_abr = QtWidgets.QCheckBox(self.groupBox_13)
        self.hss_l_abr.setChecked(True)
        self.hss_l_abr.setObjectName("hss_l_abr")
        self.gridLayout_9.addWidget(self.hss_l_abr, 3, 0, 1, 1)
        self.horizontalLayout_5.addWidget(self.groupBox_13)
        self.groupBox_14 = QtWidgets.QGroupBox(self.groupBox_11)
        self.groupBox_14.setCheckable(False)
        self.groupBox_14.setChecked(False)
        self.groupBox_14.setObjectName("groupBox_14")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.groupBox_14)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.hss_c_mse = QtWidgets.QCheckBox(self.groupBox_14)
        self.hss_c_mse.setChecked(True)
        self.hss_c_mse.setObjectName("hss_c_mse")
        self.gridLayout_10.addWidget(self.hss_c_mse, 1, 0, 1, 1)
        self.hss_c_f = QtWidgets.QCheckBox(self.groupBox_14)
        self.hss_c_f.setChecked(True)
        self.hss_c_f.setObjectName("hss_c_f")
        self.gridLayout_10.addWidget(self.hss_c_f, 0, 0, 1, 1)
        self.hss_c_mae = QtWidgets.QCheckBox(self.groupBox_14)
        self.hss_c_mae.setChecked(True)
        self.hss_c_mae.setObjectName("hss_c_mae")
        self.gridLayout_10.addWidget(self.hss_c_mae, 2, 0, 1, 1)
        self.hss_c_sqr = QtWidgets.QCheckBox(self.groupBox_14)
        self.hss_c_sqr.setChecked(True)
        self.hss_c_sqr.setObjectName("hss_c_sqr")
        self.gridLayout_10.addWidget(self.hss_c_sqr, 3, 0, 1, 1)
        self.horizontalLayout_5.addWidget(self.groupBox_14)
        self.groupBox_15 = QtWidgets.QGroupBox(self.groupBox_11)
        self.groupBox_15.setCheckable(False)
        self.groupBox_15.setChecked(False)
        self.groupBox_15.setObjectName("groupBox_15")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.groupBox_15)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.hss_mf_sqr = QtWidgets.QCheckBox(self.groupBox_15)
        self.hss_mf_sqr.setChecked(True)
        self.hss_mf_sqr.setObjectName("hss_mf_sqr")
        self.gridLayout_11.addWidget(self.hss_mf_sqr, 1, 0, 1, 1)
        self.hss_mf_n = QtWidgets.QCheckBox(self.groupBox_15)
        self.hss_mf_n.setChecked(True)
        self.hss_mf_n.setObjectName("hss_mf_n")
        self.gridLayout_11.addWidget(self.hss_mf_n, 0, 0, 1, 1)
        self.hss_mf_auto = QtWidgets.QCheckBox(self.groupBox_15)
        self.hss_mf_auto.setChecked(True)
        self.hss_mf_auto.setObjectName("hss_mf_auto")
        self.gridLayout_11.addWidget(self.hss_mf_auto, 2, 0, 1, 1)
        self.hss_mf_log2 = QtWidgets.QCheckBox(self.groupBox_15)
        self.hss_mf_log2.setChecked(True)
        self.hss_mf_log2.setObjectName("hss_mf_log2")
        self.gridLayout_11.addWidget(self.hss_mf_log2, 3, 0, 1, 1)
        self.horizontalLayout_5.addWidget(self.groupBox_15)
        self.horizontalLayout_5.setStretch(0, 1)
        self.horizontalLayout_5.setStretch(1, 1)
        self.horizontalLayout_5.setStretch(2, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.verticalLayout_2.addWidget(self.groupBox_11)
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout_4.addWidget(self.label_8, 1, 0, 1, 1)
        self.hss_fd = QtWidgets.QComboBox(self.groupBox_3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.hss_fd.setFont(font)
        self.hss_fd.setObjectName("hss_fd")
        self.hss_fd.addItem("")
        self.hss_fd.addItem("")
        self.hss_fd.addItem("")
        self.hss_fd.addItem("")
        self.hss_fd.addItem("")
        self.gridLayout_4.addWidget(self.hss_fd, 1, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout_4.addWidget(self.label_7, 0, 0, 1, 1)
        self.hss_times = QtWidgets.QLineEdit(self.groupBox_3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.hss_times.setFont(font)
        self.hss_times.setObjectName("hss_times")
        self.gridLayout_4.addWidget(self.hss_times, 0, 1, 1, 1)
        self.gridLayout_4.setColumnMinimumWidth(0, 1)
        self.gridLayout_4.setColumnMinimumWidth(1, 1)
        self.gridLayout_4.setRowMinimumHeight(0, 1)
        self.gridLayout_4.setRowMinimumHeight(1, 1)
        self.horizontalLayout_4.addLayout(self.gridLayout_4)
        self.groupBox_7 = QtWidgets.QGroupBox(self.groupBox_3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.groupBox_7.setFont(font)
        self.groupBox_7.setCheckable(False)
        self.groupBox_7.setChecked(False)
        self.groupBox_7.setObjectName("groupBox_7")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_7)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.ms_tpeButton = QtWidgets.QRadioButton(self.groupBox_7)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.ms_tpeButton.setFont(font)
        self.ms_tpeButton.setChecked(True)
        self.ms_tpeButton.setObjectName("ms_tpeButton")
        self.horizontalLayout_3.addWidget(self.ms_tpeButton)
        self.ms_rsaButton = QtWidgets.QRadioButton(self.groupBox_7)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.ms_rsaButton.setFont(font)
        self.ms_rsaButton.setObjectName("ms_rsaButton")
        self.horizontalLayout_3.addWidget(self.ms_rsaButton)
        self.ms_saButton = QtWidgets.QRadioButton(self.groupBox_7)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.ms_saButton.setFont(font)
        self.ms_saButton.setObjectName("ms_saButton")
        self.horizontalLayout_3.addWidget(self.ms_saButton)
        self.horizontalLayout_4.addWidget(self.groupBox_7)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.gridLayout_12.addWidget(self.groupBox_2, 0, 1, 1, 1)

        self.retranslateUi(WMML_gbdt)
        QtCore.QMetaObject.connectSlotsByName(WMML_gbdt)

    def retranslateUi(self, WMML_gbdt):
        _translate = QtCore.QCoreApplication.translate
        WMML_gbdt.setWindowTitle(_translate("WMML_gbdt", "WMMLgbdt"))
        self.groupBox.setTitle(_translate("WMML_gbdt", "Model Parameters"))
        self.ps_msl.setText(_translate("WMML_gbdt", "1"))
        self.ps_msl.setPlaceholderText(_translate("WMML_gbdt", "1"))
        self.label_14.setText(_translate("WMML_gbdt", "Learning Rate"))
        self.ps_mss.setText(_translate("WMML_gbdt", "2"))
        self.ps_mss.setPlaceholderText(_translate("WMML_gbdt", "2"))
        self.label_22.setText(_translate("WMML_gbdt", "Max Leaf Nodes"))
        self.ps_ss.setText(_translate("WMML_gbdt", "1.0"))
        self.ps_ss.setPlaceholderText(_translate("WMML_gbdt", "1.0"))
        self.label_6.setText(_translate("WMML_gbdt", "Min Leaf Weight Fraction"))
        self.ps_est.setText(_translate("WMML_gbdt", "100"))
        self.ps_est.setPlaceholderText(_translate("WMML_gbdt", "100"))
        self.label_5.setText(_translate("WMML_gbdt", "Min Samples Leaf"))
        self.label_21.setText(_translate("WMML_gbdt", "Min Impurity Decrease"))
        self.ps_lr.setText(_translate("WMML_gbdt", "0.1"))
        self.ps_lr.setPlaceholderText(_translate("WMML_gbdt", "0.1"))
        self.label_31.setText(_translate("WMML_gbdt", "Subsample"))
        self.ps_md.setText(_translate("WMML_gbdt", "None"))
        self.ps_md.setPlaceholderText(_translate("WMML_gbdt", "None"))
        self.ps_mid.setText(_translate("WMML_gbdt", "0.0"))
        self.ps_mid.setPlaceholderText(_translate("WMML_gbdt", "0.0"))
        self.ps_mln.setText(_translate("WMML_gbdt", "None"))
        self.ps_mln.setPlaceholderText(_translate("WMML_gbdt", "None"))
        self.label_4.setText(_translate("WMML_gbdt", "Min Samples Split"))
        self.label_3.setText(_translate("WMML_gbdt", "Max Depth"))
        self.label_2.setText(_translate("WMML_gbdt", "Number of Tree"))
        self.ps_mwfl.setText(_translate("WMML_gbdt", "0.0000"))
        self.ps_mwfl.setPlaceholderText(_translate("WMML_gbdt", "0.0000"))
        self.label_15.setText(_translate("WMML_gbdt", "Random Seed"))
        self.ps_rand.setText(_translate("WMML_gbdt", "None"))
        self.ps_rand.setPlaceholderText(_translate("WMML_gbdt", "None"))
        self.groupBox_8.setTitle(_translate("WMML_gbdt", "Loss Function"))
        self.ps_l_sqr.setText(_translate("WMML_gbdt", "Squared Error"))
        self.ps_l_hub.setText(_translate("WMML_gbdt", "Huber"))
        self.ps_l_abr.setText(_translate("WMML_gbdt", "Absolute Error"))
        self.ps_l_quat.setText(_translate("WMML_gbdt", "Quantile Error"))
        self.groupBox_9.setTitle(_translate("WMML_gbdt", "Criterion"))
        self.ps_c_f.setText(_translate("WMML_gbdt", "Friedman MSE"))
        self.ps_c_mse.setText(_translate("WMML_gbdt", "MSE"))
        self.ps_c_sqr.setText(_translate("WMML_gbdt", "Squared Error"))
        self.ps_c_mae.setText(_translate("WMML_gbdt", "MAE"))
        self.groupBox_10.setTitle(_translate("WMML_gbdt", "Max Features"))
        self.ps_mf_n.setText(_translate("WMML_gbdt", "Unconstrained"))
        self.ps_mf_auto.setText(_translate("WMML_gbdt", "Auto"))
        self.ps_mf_log2.setText(_translate("WMML_gbdt", "Log2"))
        self.ps_mf_sqr.setText(_translate("WMML_gbdt", "Square Root"))
        self.label_24.setText(_translate("WMML_gbdt", "Tolerance"))
        self.ps_tol.setText(_translate("WMML_gbdt", "0.0001"))
        self.ps_tol.setPlaceholderText(_translate("WMML_gbdt", "0.0001"))
        self.label_18.setText(_translate("WMML_gbdt", "α for Huber Loss"))
        self.ps_alpha.setText(_translate("WMML_gbdt", "0.9"))
        self.ps_alpha.setPlaceholderText(_translate("WMML_gbdt", "0.9"))
        self.groupBox_12.setTitle(_translate("WMML_gbdt", "Initial Model"))
        self.f_load.setText(_translate("WMML_gbdt", "Load Model"))
        self.addButton_2.setText(_translate("WMML_gbdt", "Update Model"))
        self.addButton_3.setText(_translate("WMML_gbdt", "Default"))
        self.label_27.setText(_translate("WMML_gbdt", "Model Name"))
        self.label_26.setText(_translate("WMML_gbdt", "Loaded Model"))
        self.label_28.setText(_translate("WMML_gbdt", "Initial Model"))
        self.jzsdf.setText(_translate("WMML_gbdt", "Send Model"))
        self.infobox.setText(_translate("WMML_gbdt", "....."))
        self.groupBox_2.setTitle(_translate("WMML_gbdt", "Enable Optimazation"))
        self.groupBox_11.setTitle(_translate("WMML_gbdt", "Space"))
        self.hss_mss_max.setText(_translate("WMML_gbdt", "15"))
        self.hss_mss_max.setPlaceholderText(_translate("WMML_gbdt", "15"))
        self.hss_alpha_min.setText(_translate("WMML_gbdt", "0.2"))
        self.hss_alpha_min.setPlaceholderText(_translate("WMML_gbdt", "0.2"))
        self.hss_msl_min.setText(_translate("WMML_gbdt", "2"))
        self.hss_msl_min.setPlaceholderText(_translate("WMML_gbdt", "2"))
        self.label_32.setText(_translate("WMML_gbdt", "Subsample"))
        self.label_13.setText(_translate("WMML_gbdt", "Min Leaf Weight Fraction"))
        self.label_11.setText(_translate("WMML_gbdt", "Min Samples Split"))
        self.hss_alpha_max.setText(_translate("WMML_gbdt", "1.0"))
        self.hss_alpha_max.setPlaceholderText(_translate("WMML_gbdt", "1.0"))
        self.hss_md_max.setText(_translate("WMML_gbdt", "32"))
        self.hss_md_max.setPlaceholderText(_translate("WMML_gbdt", "32"))
        self.hss_mwfl_min.setText(_translate("WMML_gbdt", "0.0000"))
        self.hss_mwfl_min.setPlaceholderText(_translate("WMML_gbdt", "0.0000"))
        self.label_19.setText(_translate("WMML_gbdt", "Max Leaf Nodes"))
        self.hss_mss_min.setText(_translate("WMML_gbdt", "2"))
        self.hss_mss_min.setPlaceholderText(_translate("WMML_gbdt", "2"))
        self.hss_mid_max.setText(_translate("WMML_gbdt", "0.0001"))
        self.hss_mid_max.setPlaceholderText(_translate("WMML_gbdt", "0.0001"))
        self.hss_mln_min.setText(_translate("WMML_gbdt", "2"))
        self.hss_mln_min.setPlaceholderText(_translate("WMML_gbdt", "2"))
        self.label_12.setText(_translate("WMML_gbdt", "Min Samples Leaf"))
        self.label_16.setText(_translate("WMML_gbdt", "Min"))
        self.hss_est_max.setText(_translate("WMML_gbdt", "1000"))
        self.hss_est_max.setPlaceholderText(_translate("WMML_gbdt", "1000"))
        self.hss_mid_min.setText(_translate("WMML_gbdt", "0.0000"))
        self.hss_mid_min.setPlaceholderText(_translate("WMML_gbdt", "0.0000"))
        self.label_35.setText(_translate("WMML_gbdt", "α for Huber Loss"))
        self.hss_mwfl_max.setText(_translate("WMML_gbdt", "0.0001"))
        self.hss_mwfl_max.setPlaceholderText(_translate("WMML_gbdt", "0.0001"))
        self.label_17.setText(_translate("WMML_gbdt", "Max"))
        self.hss_ss_max.setText(_translate("WMML_gbdt", "1.0"))
        self.hss_ss_max.setPlaceholderText(_translate("WMML_gbdt", "1.0"))
        self.hss_msl_max.setText(_translate("WMML_gbdt", "15"))
        self.hss_msl_max.setPlaceholderText(_translate("WMML_gbdt", "15"))
        self.label_30.setText(_translate("WMML_gbdt", "Learning Rate"))
        self.hss_mln_max.setText(_translate("WMML_gbdt", "50"))
        self.hss_mln_max.setPlaceholderText(_translate("WMML_gbdt", "50"))
        self.hss_lr_max.setText(_translate("WMML_gbdt", "1.00"))
        self.hss_lr_max.setPlaceholderText(_translate("WMML_gbdt", "1.00"))
        self.label_10.setText(_translate("WMML_gbdt", "Max Depth"))
        self.hss_lr_min.setText(_translate("WMML_gbdt", "0.01"))
        self.hss_lr_min.setPlaceholderText(_translate("WMML_gbdt", "0.01"))
        self.hss_ss_min.setText(_translate("WMML_gbdt", "0.5"))
        self.hss_ss_min.setPlaceholderText(_translate("WMML_gbdt", "0.5"))
        self.hss_md_min.setText(_translate("WMML_gbdt", "1"))
        self.hss_md_min.setPlaceholderText(_translate("WMML_gbdt", "1"))
        self.label_9.setText(_translate("WMML_gbdt", "Number of Tree"))
        self.hss_est_min.setText(_translate("WMML_gbdt", "10"))
        self.hss_est_min.setPlaceholderText(_translate("WMML_gbdt", "10"))
        self.label_20.setText(_translate("WMML_gbdt", "Min Impurity Decrease"))
        self.label_33.setText(_translate("WMML_gbdt", "Tolerance"))
        self.hss_tol_min.setText(_translate("WMML_gbdt", "0.00001"))
        self.hss_tol_min.setPlaceholderText(_translate("WMML_gbdt", "0.00001"))
        self.hss_tol_max.setText(_translate("WMML_gbdt", "0.001"))
        self.hss_tol_max.setPlaceholderText(_translate("WMML_gbdt", "0.001"))
        self.groupBox_13.setTitle(_translate("WMML_gbdt", "Loss Function"))
        self.hss_l_quat.setText(_translate("WMML_gbdt", "Quantile Error"))
        self.hss_l_sqr.setText(_translate("WMML_gbdt", "Squared Error"))
        self.hss_l_hub.setText(_translate("WMML_gbdt", "Huber"))
        self.hss_l_abr.setText(_translate("WMML_gbdt", "Absolute Error"))
        self.groupBox_14.setTitle(_translate("WMML_gbdt", "Criterion"))
        self.hss_c_mse.setText(_translate("WMML_gbdt", "MSE"))
        self.hss_c_f.setText(_translate("WMML_gbdt", "Friedman MSE"))
        self.hss_c_mae.setText(_translate("WMML_gbdt", "MAE"))
        self.hss_c_sqr.setText(_translate("WMML_gbdt", "Squared Error"))
        self.groupBox_15.setTitle(_translate("WMML_gbdt", "Max Features"))
        self.hss_mf_sqr.setText(_translate("WMML_gbdt", "Square Root"))
        self.hss_mf_n.setText(_translate("WMML_gbdt", "Unconstrained"))
        self.hss_mf_auto.setText(_translate("WMML_gbdt", "Auto"))
        self.hss_mf_log2.setText(_translate("WMML_gbdt", "Log2"))
        self.groupBox_3.setTitle(_translate("WMML_gbdt", "Parameters"))
        self.label_8.setText(_translate("WMML_gbdt", "Folds"))
        self.hss_fd.setItemText(0, _translate("WMML_gbdt", "2"))
        self.hss_fd.setItemText(1, _translate("WMML_gbdt", "3"))
        self.hss_fd.setItemText(2, _translate("WMML_gbdt", "5"))
        self.hss_fd.setItemText(3, _translate("WMML_gbdt", "10"))
        self.hss_fd.setItemText(4, _translate("WMML_gbdt", "20"))
        self.label_7.setText(_translate("WMML_gbdt", "Times"))
        self.hss_times.setText(_translate("WMML_gbdt", "20"))
        self.hss_times.setPlaceholderText(_translate("WMML_gbdt", "20"))
        self.groupBox_7.setTitle(_translate("WMML_gbdt", "Algorithms"))
        self.ms_tpeButton.setText(_translate("WMML_gbdt", "TPE"))
        self.ms_rsaButton.setText(_translate("WMML_gbdt", "Random"))
        self.ms_saButton.setText(_translate("WMML_gbdt", "Adaptive"))
