from PyQt5 import QtCore, QtGui, QtWidgets


# noinspection PyUnresolvedReferences
class Ui_WMML_knn(object):
    def setupUi(self, WMML_knn):
        WMML_knn.setObjectName("WMML_knn")
        WMML_knn.resize(536, 637)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(WMML_knn.sizePolicy().hasHeightForWidth())
        WMML_knn.setSizePolicy(sizePolicy)
        WMML_knn.setMinimumSize(QtCore.QSize(536, 637))
        WMML_knn.setMaximumSize(QtCore.QSize(557, 637))
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(WMML_knn)
        self.verticalLayout_9.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.groupBox = QtWidgets.QGroupBox(WMML_knn)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(178, 589))
        self.groupBox.setMaximumSize(QtCore.QSize(178, 589))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.ps_n = QtWidgets.QLineEdit(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.ps_n.setFont(font)
        self.ps_n.setObjectName("ps_n")
        self.horizontalLayout.addWidget(self.ps_n)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.ps_a_auto = QtWidgets.QRadioButton(self.groupBox_4)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.ps_a_auto.setFont(font)
        self.ps_a_auto.setChecked(True)
        self.ps_a_auto.setObjectName("ps_a_auto")
        self.verticalLayout.addWidget(self.ps_a_auto)
        self.ps_a_bt = QtWidgets.QRadioButton(self.groupBox_4)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.ps_a_bt.setFont(font)
        self.ps_a_bt.setChecked(False)
        self.ps_a_bt.setObjectName("ps_a_bt")
        self.verticalLayout.addWidget(self.ps_a_bt)
        self.ps_a_kt = QtWidgets.QRadioButton(self.groupBox_4)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.ps_a_kt.setFont(font)
        self.ps_a_kt.setObjectName("ps_a_kt")
        self.verticalLayout.addWidget(self.ps_a_kt)
        self.ps_a_bru = QtWidgets.QRadioButton(self.groupBox_4)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.ps_a_bru.setFont(font)
        self.ps_a_bru.setObjectName("ps_a_bru")
        self.verticalLayout.addWidget(self.ps_a_bru)
        self.verticalLayout_3.addWidget(self.groupBox_4)
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.groupBox_6.setFont(font)
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.ps_m_eucl = QtWidgets.QRadioButton(self.groupBox_6)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.ps_m_eucl.setFont(font)
        self.ps_m_eucl.setChecked(True)
        self.ps_m_eucl.setObjectName("ps_m_eucl")
        self.verticalLayout_2.addWidget(self.ps_m_eucl)
        self.ps_m_manh = QtWidgets.QRadioButton(self.groupBox_6)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.ps_m_manh.setFont(font)
        self.ps_m_manh.setChecked(False)
        self.ps_m_manh.setObjectName("ps_m_manh")
        self.verticalLayout_2.addWidget(self.ps_m_manh)
        self.ps_m_cheb = QtWidgets.QRadioButton(self.groupBox_6)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.ps_m_cheb.setFont(font)
        self.ps_m_cheb.setObjectName("ps_m_cheb")
        self.verticalLayout_2.addWidget(self.ps_m_cheb)
        self.ps_m_mink = QtWidgets.QRadioButton(self.groupBox_6)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.ps_m_mink.setFont(font)
        self.ps_m_mink.setObjectName("ps_m_mink")
        self.verticalLayout_2.addWidget(self.ps_m_mink)
        self.ps_m_wink = QtWidgets.QRadioButton(self.groupBox_6)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.ps_m_wink.setFont(font)
        self.ps_m_wink.setObjectName("ps_m_wink")
        self.verticalLayout_2.addWidget(self.ps_m_wink)
        self.ps_m_seuc = QtWidgets.QRadioButton(self.groupBox_6)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.ps_m_seuc.setFont(font)
        self.ps_m_seuc.setObjectName("ps_m_seuc")
        self.verticalLayout_2.addWidget(self.ps_m_seuc)
        self.ps_m_mah = QtWidgets.QRadioButton(self.groupBox_6)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.ps_m_mah.setFont(font)
        self.ps_m_mah.setObjectName("ps_m_mah")
        self.verticalLayout_2.addWidget(self.ps_m_mah)
        self.verticalLayout_3.addWidget(self.groupBox_6)
        self.groupBox_8 = QtWidgets.QGroupBox(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.groupBox_8.setFont(font)
        self.groupBox_8.setObjectName("groupBox_8")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_8)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.ps_w_uni = QtWidgets.QRadioButton(self.groupBox_8)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.ps_w_uni.setFont(font)
        self.ps_w_uni.setChecked(True)
        self.ps_w_uni.setObjectName("ps_w_uni")
        self.verticalLayout_4.addWidget(self.ps_w_uni)
        self.ps_w_dis = QtWidgets.QRadioButton(self.groupBox_8)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.ps_w_dis.setFont(font)
        self.ps_w_dis.setChecked(False)
        self.ps_w_dis.setObjectName("ps_w_dis")
        self.verticalLayout_4.addWidget(self.ps_w_dis)
        self.verticalLayout_3.addWidget(self.groupBox_8)
        self.horizontalLayout_5.addWidget(self.groupBox)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.groupBox_2 = QtWidgets.QGroupBox(WMML_knn)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(325, 552))
        self.groupBox_2.setMaximumSize(QtCore.QSize(325, 552))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.groupBox_2.setFont(font)
        self.groupBox_2.setCheckable(True)
        self.groupBox_2.setChecked(False)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout_4.addWidget(self.label_8, 1, 0, 1, 1)
        self.hss_fd = QtWidgets.QComboBox(self.groupBox_3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.hss_fd.setFont(font)
        self.hss_fd.setObjectName("hss_fd")
        self.hss_fd.addItem("")
        self.hss_fd.addItem("")
        self.hss_fd.addItem("")
        self.hss_fd.addItem("")
        self.hss_fd.addItem("")
        self.gridLayout_4.addWidget(self.hss_fd, 1, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout_4.addWidget(self.label_7, 0, 0, 1, 1)
        self.hss_times = QtWidgets.QLineEdit(self.groupBox_3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.hss_times.setFont(font)
        self.hss_times.setObjectName("hss_times")
        self.gridLayout_4.addWidget(self.hss_times, 0, 1, 1, 1)
        self.gridLayout_4.setColumnMinimumWidth(0, 1)
        self.gridLayout_4.setColumnMinimumWidth(1, 1)
        self.gridLayout_4.setRowMinimumHeight(0, 1)
        self.gridLayout_4.setRowMinimumHeight(1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout_4)
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox_3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.groupBox_5.setFont(font)
        self.groupBox_5.setCheckable(False)
        self.groupBox_5.setChecked(False)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.ms_tpeButton = QtWidgets.QRadioButton(self.groupBox_5)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.ms_tpeButton.setFont(font)
        self.ms_tpeButton.setChecked(True)
        self.ms_tpeButton.setObjectName("ms_tpeButton")
        self.verticalLayout_14.addWidget(self.ms_tpeButton)
        self.ms_rsaButton = QtWidgets.QRadioButton(self.groupBox_5)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.ms_rsaButton.setFont(font)
        self.ms_rsaButton.setObjectName("ms_rsaButton")
        self.verticalLayout_14.addWidget(self.ms_rsaButton)
        self.ms_saButton = QtWidgets.QRadioButton(self.groupBox_5)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.ms_saButton.setFont(font)
        self.ms_saButton.setObjectName("ms_saButton")
        self.verticalLayout_14.addWidget(self.ms_saButton)
        self.horizontalLayout_3.addWidget(self.groupBox_5)
        self.verticalLayout_8.addWidget(self.groupBox_3)
        self.groupBox_9 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_9.setObjectName("groupBox_9")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_9)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_9 = QtWidgets.QLabel(self.groupBox_9)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_2.addWidget(self.label_9)
        self.label_16 = QtWidgets.QLabel(self.groupBox_9)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_2.addWidget(self.label_16)
        self.hss_n_min = QtWidgets.QLineEdit(self.groupBox_9)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.hss_n_min.setFont(font)
        self.hss_n_min.setObjectName("hss_n_min")
        self.horizontalLayout_2.addWidget(self.hss_n_min)
        self.label_17 = QtWidgets.QLabel(self.groupBox_9)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_2.addWidget(self.label_17)
        self.hss_n_max = QtWidgets.QLineEdit(self.groupBox_9)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.hss_n_max.setFont(font)
        self.hss_n_max.setObjectName("hss_n_max")
        self.horizontalLayout_2.addWidget(self.hss_n_max)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 1)
        self.horizontalLayout_2.setStretch(2, 3)
        self.horizontalLayout_2.setStretch(3, 1)
        self.horizontalLayout_2.setStretch(4, 3)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.groupBox_7 = QtWidgets.QGroupBox(self.groupBox_9)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.groupBox_7.setFont(font)
        self.groupBox_7.setObjectName("groupBox_7")
        self.hss_m_euc = QtWidgets.QCheckBox(self.groupBox_7)
        self.hss_m_euc.setGeometry(QtCore.QRect(12, 29, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.hss_m_euc.setFont(font)
        self.hss_m_euc.setChecked(True)
        self.hss_m_euc.setObjectName("hss_m_euc")
        self.hss_m_manh = QtWidgets.QCheckBox(self.groupBox_7)
        self.hss_m_manh.setGeometry(QtCore.QRect(12, 57, 94, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.hss_m_manh.setFont(font)
        self.hss_m_manh.setChecked(True)
        self.hss_m_manh.setObjectName("hss_m_manh")
        self.hss_m_cheb = QtWidgets.QCheckBox(self.groupBox_7)
        self.hss_m_cheb.setGeometry(QtCore.QRect(12, 85, 100, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.hss_m_cheb.setFont(font)
        self.hss_m_cheb.setChecked(True)
        self.hss_m_cheb.setObjectName("hss_m_cheb")
        self.hss_m_mink = QtWidgets.QCheckBox(self.groupBox_7)
        self.hss_m_mink.setGeometry(QtCore.QRect(12, 113, 93, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.hss_m_mink.setFont(font)
        self.hss_m_mink.setChecked(True)
        self.hss_m_mink.setObjectName("hss_m_mink")
        self.hss_m_wink = QtWidgets.QCheckBox(self.groupBox_7)
        self.hss_m_wink.setGeometry(QtCore.QRect(12, 141, 93, 38))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.hss_m_wink.setFont(font)
        self.hss_m_wink.setChecked(True)
        self.hss_m_wink.setObjectName("hss_m_wink")
        self.hss_m_seuc = QtWidgets.QCheckBox(self.groupBox_7)
        self.hss_m_seuc.setGeometry(QtCore.QRect(12, 186, 91, 38))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.hss_m_seuc.setFont(font)
        self.hss_m_seuc.setChecked(True)
        self.hss_m_seuc.setObjectName("hss_m_seuc")
        self.hss_m_maha = QtWidgets.QCheckBox(self.groupBox_7)
        self.hss_m_maha.setGeometry(QtCore.QRect(12, 231, 108, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.hss_m_maha.setFont(font)
        self.hss_m_maha.setChecked(True)
        self.hss_m_maha.setObjectName("hss_m_maha")
        self.horizontalLayout_4.addWidget(self.groupBox_7)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.groupBox_11 = QtWidgets.QGroupBox(self.groupBox_9)
        self.groupBox_11.setObjectName("groupBox_11")
        self.hss_a_auto = QtWidgets.QCheckBox(self.groupBox_11)
        self.hss_a_auto.setGeometry(QtCore.QRect(20, 30, 61, 21))
        self.hss_a_auto.setChecked(True)
        self.hss_a_auto.setObjectName("hss_a_auto")
        self.hss_a_bt = QtWidgets.QCheckBox(self.groupBox_11)
        self.hss_a_bt.setGeometry(QtCore.QRect(20, 60, 101, 21))
        self.hss_a_bt.setChecked(True)
        self.hss_a_bt.setObjectName("hss_a_bt")
        self.hss_a_kt = QtWidgets.QCheckBox(self.groupBox_11)
        self.hss_a_kt.setGeometry(QtCore.QRect(20, 90, 101, 21))
        self.hss_a_kt.setChecked(True)
        self.hss_a_kt.setObjectName("hss_a_kt")
        self.hss_a_bru = QtWidgets.QCheckBox(self.groupBox_11)
        self.hss_a_bru.setGeometry(QtCore.QRect(20, 120, 101, 21))
        self.hss_a_bru.setChecked(True)
        self.hss_a_bru.setObjectName("hss_a_bru")
        self.verticalLayout_5.addWidget(self.groupBox_11)
        self.groupBox_10 = QtWidgets.QGroupBox(self.groupBox_9)
        self.groupBox_10.setObjectName("groupBox_10")
        self.hss_m_uni = QtWidgets.QCheckBox(self.groupBox_10)
        self.hss_m_uni.setGeometry(QtCore.QRect(20, 20, 111, 31))
        self.hss_m_uni.setChecked(True)
        self.hss_m_uni.setObjectName("hss_m_uni")
        self.hss_m_dis = QtWidgets.QCheckBox(self.groupBox_10)
        self.hss_m_dis.setGeometry(QtCore.QRect(20, 50, 101, 31))
        self.hss_m_dis.setChecked(True)
        self.hss_m_dis.setObjectName("hss_m_dis")
        self.verticalLayout_5.addWidget(self.groupBox_10)
        self.verticalLayout_5.setStretch(0, 2)
        self.verticalLayout_5.setStretch(1, 1)
        self.horizontalLayout_4.addLayout(self.verticalLayout_5)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.verticalLayout_8.addWidget(self.groupBox_9)
        self.verticalLayout_7.addWidget(self.groupBox_2)
        self.jzsdf = QtWidgets.QPushButton(WMML_knn)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.jzsdf.setFont(font)
        self.jzsdf.setObjectName("jzsdf")
        self.verticalLayout_7.addWidget(self.jzsdf)
        self.horizontalLayout_5.addLayout(self.verticalLayout_7)
        self.verticalLayout_9.addLayout(self.horizontalLayout_5)
        self.infobox = QtWidgets.QLabel(WMML_knn)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.infobox.setFont(font)
        self.infobox.setObjectName("infobox")
        self.verticalLayout_9.addWidget(self.infobox)

        self.retranslateUi(WMML_knn)
        QtCore.QMetaObject.connectSlotsByName(WMML_knn)

    def retranslateUi(self, WMML_knn):
        _translate = QtCore.QCoreApplication.translate
        WMML_knn.setWindowTitle(_translate("WMML_knn", "WMMLknn"))
        self.groupBox.setTitle(_translate("WMML_knn", "Model Parameters"))
        self.label_2.setText(_translate("WMML_knn", "Neighbors:"))
        self.ps_n.setText(_translate("WMML_knn", "5"))
        self.ps_n.setPlaceholderText(_translate("WMML_knn", "5"))
        self.groupBox_4.setTitle(_translate("WMML_knn", "Algorithms"))
        self.ps_a_auto.setText(_translate("WMML_knn", "Auto"))
        self.ps_a_bt.setText(_translate("WMML_knn", "Ball-Tree"))
        self.ps_a_kt.setText(_translate("WMML_knn", "KD-Tree"))
        self.ps_a_bru.setText(_translate("WMML_knn", "Brute"))
        self.groupBox_6.setTitle(_translate("WMML_knn", "Metric"))
        self.ps_m_eucl.setText(_translate("WMML_knn", "Euclidean"))
        self.ps_m_manh.setText(_translate("WMML_knn", "Manhattan"))
        self.ps_m_cheb.setText(_translate("WMML_knn", "Chebyshev"))
        self.ps_m_mink.setText(_translate("WMML_knn", "Minkowski"))
        self.ps_m_wink.setText(_translate("WMML_knn", "Weighted\n"
"Minkowski"))
        self.ps_m_seuc.setText(_translate("WMML_knn", "Standard\n"
"Euclidean"))
        self.ps_m_mah.setText(_translate("WMML_knn", "Mahalanobis"))
        self.groupBox_8.setTitle(_translate("WMML_knn", "Weights"))
        self.ps_w_uni.setText(_translate("WMML_knn", "Uniform"))
        self.ps_w_dis.setText(_translate("WMML_knn", "Distance"))
        self.groupBox_2.setTitle(_translate("WMML_knn", "Enable Optimazation"))
        self.groupBox_3.setTitle(_translate("WMML_knn", "Parameters"))
        self.label_8.setText(_translate("WMML_knn", "Folds"))
        self.hss_fd.setItemText(0, _translate("WMML_knn", "2"))
        self.hss_fd.setItemText(1, _translate("WMML_knn", "3"))
        self.hss_fd.setItemText(2, _translate("WMML_knn", "5"))
        self.hss_fd.setItemText(3, _translate("WMML_knn", "10"))
        self.hss_fd.setItemText(4, _translate("WMML_knn", "20"))
        self.label_7.setText(_translate("WMML_knn", "Times"))
        self.hss_times.setText(_translate("WMML_knn", "20"))
        self.hss_times.setPlaceholderText(_translate("WMML_knn", "20"))
        self.groupBox_5.setTitle(_translate("WMML_knn", "Algorithms"))
        self.ms_tpeButton.setText(_translate("WMML_knn", "TPE"))
        self.ms_rsaButton.setText(_translate("WMML_knn", "Random"))
        self.ms_saButton.setText(_translate("WMML_knn", "Adaptive"))
        self.groupBox_9.setTitle(_translate("WMML_knn", "Space"))
        self.label_9.setText(_translate("WMML_knn", "Neighbors:"))
        self.label_16.setText(_translate("WMML_knn", "Min"))
        self.hss_n_min.setText(_translate("WMML_knn", "2"))
        self.hss_n_min.setPlaceholderText(_translate("WMML_knn", "2"))
        self.label_17.setText(_translate("WMML_knn", "Max"))
        self.hss_n_max.setText(_translate("WMML_knn", "15"))
        self.hss_n_max.setPlaceholderText(_translate("WMML_knn", "15"))
        self.groupBox_7.setTitle(_translate("WMML_knn", "Metric"))
        self.hss_m_euc.setText(_translate("WMML_knn", "Euclidean"))
        self.hss_m_manh.setText(_translate("WMML_knn", "Manhattan"))
        self.hss_m_cheb.setText(_translate("WMML_knn", "Chebyshev"))
        self.hss_m_mink.setText(_translate("WMML_knn", "Minkowski"))
        self.hss_m_wink.setText(_translate("WMML_knn", "Weighted\n"
"Minkowski"))
        self.hss_m_seuc.setText(_translate("WMML_knn", "Standard\n"
"Euclidean"))
        self.hss_m_maha.setText(_translate("WMML_knn", "Mahalanobis"))
        self.groupBox_11.setTitle(_translate("WMML_knn", "Algorithms"))
        self.hss_a_auto.setText(_translate("WMML_knn", "Auto"))
        self.hss_a_bt.setText(_translate("WMML_knn", "Ball-Tree"))
        self.hss_a_kt.setText(_translate("WMML_knn", "KD-Tree"))
        self.hss_a_bru.setText(_translate("WMML_knn", "Brute"))
        self.groupBox_10.setTitle(_translate("WMML_knn", "Weights"))
        self.hss_m_uni.setText(_translate("WMML_knn", "Uniform"))
        self.hss_m_dis.setText(_translate("WMML_knn", "Distance"))
        self.jzsdf.setText(_translate("WMML_knn", "Send Model"))
        self.infobox.setText(_translate("WMML_knn", "....."))
