from PyQt5 import QtCore, QtGui, QtWidgets


# noinspection PyUnresolvedReferences
class Ui_WMML_prediction(object):
    def setupUi(self, WMML_prediction):
        WMML_prediction.setObjectName("WMML_prediction")
        WMML_prediction.resize(730, 660)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(WMML_prediction)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.jzdst = QtWidgets.QPushButton(WMML_prediction)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.jzdst.setFont(font)
        self.jzdst.setObjectName("jzdst")
        self.verticalLayout_2.addWidget(self.jzdst)
        self.jzrld_btn = QtWidgets.QPushButton(WMML_prediction)
        self.jzrld_btn.setMinimumSize(QtCore.QSize(195, 28))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.jzrld_btn.setFont(font)
        self.jzrld_btn.setObjectName("jzrld_btn")
        self.verticalLayout_2.addWidget(self.jzrld_btn)
        self.jzatm_btn = QtWidgets.QPushButton(WMML_prediction)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.jzatm_btn.setFont(font)
        self.jzatm_btn.setObjectName("jzatm_btn")
        self.verticalLayout_2.addWidget(self.jzatm_btn)
        self.pd_pred_btn = QtWidgets.QPushButton(WMML_prediction)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.pd_pred_btn.setFont(font)
        self.pd_pred_btn.setObjectName("pd_pred_btn")
        self.verticalLayout_2.addWidget(self.pd_pred_btn)
        self.jzsdd = QtWidgets.QPushButton(WMML_prediction)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.jzsdd.setFont(font)
        self.jzsdd.setObjectName("jzsdd")
        self.verticalLayout_2.addWidget(self.jzsdd)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.label = QtWidgets.QLabel(WMML_prediction)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.pd_param_tab1 = QtWidgets.QTextBrowser(WMML_prediction)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pd_param_tab1.sizePolicy().hasHeightForWidth())
        self.pd_param_tab1.setSizePolicy(sizePolicy)
        self.pd_param_tab1.setMinimumSize(QtCore.QSize(0, 60))
        self.pd_param_tab1.setObjectName("pd_param_tab1")
        self.verticalLayout_2.addWidget(self.pd_param_tab1)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_47 = QtWidgets.QLabel(WMML_prediction)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_47.sizePolicy().hasHeightForWidth())
        self.label_47.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_47.setFont(font)
        self.label_47.setObjectName("label_47")
        self.verticalLayout.addWidget(self.label_47)
        self.jz_od_tab = QtWidgets.QTableView(WMML_prediction)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.jz_od_tab.sizePolicy().hasHeightForWidth())
        self.jz_od_tab.setSizePolicy(sizePolicy)
        self.jz_od_tab.setSizeIncrement(QtCore.QSize(0, 20))
        self.jz_od_tab.setObjectName("jz_od_tab")
        self.verticalLayout.addWidget(self.jz_od_tab)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 8)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout()
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.label_53 = QtWidgets.QLabel(WMML_prediction)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_53.sizePolicy().hasHeightForWidth())
        self.label_53.setSizePolicy(sizePolicy)
        self.label_53.setMinimumSize(QtCore.QSize(0, 32))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_53.setFont(font)
        self.label_53.setObjectName("label_53")
        self.verticalLayout_22.addWidget(self.label_53)
        self.pd_param_tab2 = QtWidgets.QTextBrowser(WMML_prediction)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pd_param_tab2.sizePolicy().hasHeightForWidth())
        self.pd_param_tab2.setSizePolicy(sizePolicy)
        self.pd_param_tab2.setMinimumSize(QtCore.QSize(130, 0))
        self.pd_param_tab2.setObjectName("pd_param_tab2")
        self.verticalLayout_22.addWidget(self.pd_param_tab2)
        self.horizontalLayout.addLayout(self.verticalLayout_22)
        self.verticalLayout_23 = QtWidgets.QVBoxLayout()
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.label_46 = QtWidgets.QLabel(WMML_prediction)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_46.sizePolicy().hasHeightForWidth())
        self.label_46.setSizePolicy(sizePolicy)
        self.label_46.setMinimumSize(QtCore.QSize(0, 32))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_46.setFont(font)
        self.label_46.setObjectName("label_46")
        self.verticalLayout_23.addWidget(self.label_46)
        self.pd_fd_tab = QtWidgets.QTableView(WMML_prediction)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pd_fd_tab.sizePolicy().hasHeightForWidth())
        self.pd_fd_tab.setSizePolicy(sizePolicy)
        self.pd_fd_tab.setObjectName("pd_fd_tab")
        self.verticalLayout_23.addWidget(self.pd_fd_tab)
        self.horizontalLayout.addLayout(self.verticalLayout_23)
        self.verticalLayout_24 = QtWidgets.QVBoxLayout()
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.label_45 = QtWidgets.QLabel(WMML_prediction)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_45.sizePolicy().hasHeightForWidth())
        self.label_45.setSizePolicy(sizePolicy)
        self.label_45.setMinimumSize(QtCore.QSize(0, 32))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_45.setFont(font)
        self.label_45.setObjectName("label_45")
        self.verticalLayout_24.addWidget(self.label_45)
        self.pd_pd_tab = QtWidgets.QTableView(WMML_prediction)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pd_pd_tab.sizePolicy().hasHeightForWidth())
        self.pd_pd_tab.setSizePolicy(sizePolicy)
        self.pd_pd_tab.setObjectName("pd_pd_tab")
        self.verticalLayout_24.addWidget(self.pd_pd_tab)
        self.horizontalLayout.addLayout(self.verticalLayout_24)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 5)
        self.horizontalLayout.setStretch(2, 2)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout_3.setStretch(0, 1)
        self.verticalLayout_3.setStretch(1, 3)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.infobox = QtWidgets.QLabel(WMML_prediction)
        self.infobox.setObjectName("infobox")
        self.verticalLayout_4.addWidget(self.infobox)

        self.retranslateUi(WMML_prediction)
        QtCore.QMetaObject.connectSlotsByName(WMML_prediction)

    def retranslateUi(self, WMML_prediction):
        _translate = QtCore.QCoreApplication.translate
        WMML_prediction.setWindowTitle(_translate("WMML_prediction", "WMMLprediction"))
        self.jzdst.setText(_translate("WMML_prediction", "Reload Data"))
        self.jzrld_btn.setText(_translate("WMML_prediction", "Reload Model"))
        self.jzatm_btn.setText(_translate("WMML_prediction", "Auto Match"))
        self.pd_pred_btn.setText(_translate("WMML_prediction", "Prediction"))
        self.jzsdd.setText(_translate("WMML_prediction", "Save Data"))
        self.label.setText(_translate("WMML_prediction", "Model"))
        self.label_47.setText(_translate("WMML_prediction", "Dataset"))
        self.label_53.setText(_translate("WMML_prediction", "Model Features"))
        self.label_46.setText(_translate("WMML_prediction", "Features"))
        self.label_45.setText(_translate("WMML_prediction", "Prediction"))
        self.infobox.setText(_translate("WMML_prediction", "....."))
