from PyQt5 import QtCore, QtGui, QtWidgets


# noinspection PyUnresolvedReferences
class Ui_WMML_prep(object):
    def setupUi(self, WMML_prep):
        WMML_prep.setObjectName("WMML_prep")
        WMML_prep.resize(730, 668)
        WMML_prep.setMinimumSize(QtCore.QSize(730, 660))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon/input_data.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        WMML_prep.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(WMML_prep)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(WMML_prep)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.jzfucbx = QtWidgets.QComboBox(WMML_prep)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.jzfucbx.setFont(font)
        self.jzfucbx.setObjectName("jzfucbx")
        self.jzfucbx.addItem("")
        self.jzfucbx.addItem("")
        self.jzfucbx.addItem("")
        self.jzfucbx.addItem("")
        self.jzfucbx.addItem("")
        self.jzfucbx.addItem("")
        self.jzfucbx.addItem("")
        self.jzfucbx.addItem("")
        self.jzfucbx.addItem("")
        self.jzfucbx.addItem("")
        self.verticalLayout.addWidget(self.jzfucbx)
        self.jzadfun = QtWidgets.QPushButton(WMML_prep)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.jzadfun.setFont(font)
        self.jzadfun.setObjectName("jzadfun")
        self.verticalLayout.addWidget(self.jzadfun)
        self.jzadfb = QtWidgets.QPushButton(WMML_prep)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.jzadfb.setFont(font)
        self.jzadfb.setObjectName("jzadfb")
        self.verticalLayout.addWidget(self.jzadfb)
        self.jzcptfb = QtWidgets.QPushButton(WMML_prep)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.jzcptfb.setFont(font)
        self.jzcptfb.setObjectName("jzcptfb")
        self.verticalLayout.addWidget(self.jzcptfb)
        self.jzsdf = QtWidgets.QPushButton(WMML_prep)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.jzsdf.sizePolicy().hasHeightForWidth())
        self.jzsdf.setSizePolicy(sizePolicy)
        self.jzsdf.setMinimumSize(QtCore.QSize(195, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.jzsdf.setFont(font)
        self.jzsdf.setIconSize(QtCore.QSize(42, 42))
        self.jzsdf.setFlat(False)
        self.jzsdf.setObjectName("jzsdf")
        self.verticalLayout.addWidget(self.jzsdf)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_3 = QtWidgets.QLabel(WMML_prep)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_5.addWidget(self.label_3)
        self.nfnld = QtWidgets.QLineEdit(WMML_prep)
        self.nfnld.setObjectName("nfnld")
        self.verticalLayout_5.addWidget(self.nfnld)
        self.label_4 = QtWidgets.QLabel(WMML_prep)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_5.addWidget(self.label_4)
        self.jzfuncedit = QtWidgets.QTextEdit(WMML_prep)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.jzfuncedit.sizePolicy().hasHeightForWidth())
        self.jzfuncedit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.jzfuncedit.setFont(font)
        self.jzfuncedit.setObjectName("jzfuncedit")
        self.verticalLayout_5.addWidget(self.jzfuncedit)
        self.horizontalLayout_3.addLayout(self.verticalLayout_5)
        self.jzns = QtWidgets.QGroupBox(WMML_prep)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.jzns.setFont(font)
        self.jzns.setCheckable(True)
        self.jzns.setObjectName("jzns")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.jzns)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.jzns_std = QtWidgets.QRadioButton(self.jzns)
        self.jzns_std.setObjectName("jzns_std")
        self.verticalLayout_7.addWidget(self.jzns_std)
        self.jzns_ctr = QtWidgets.QRadioButton(self.jzns)
        self.jzns_ctr.setChecked(True)
        self.jzns_ctr.setObjectName("jzns_ctr")
        self.verticalLayout_7.addWidget(self.jzns_ctr)
        self.jzns_sle = QtWidgets.QRadioButton(self.jzns)
        self.jzns_sle.setObjectName("jzns_sle")
        self.verticalLayout_7.addWidget(self.jzns_sle)
        self.jzns_nmlf = QtWidgets.QRadioButton(self.jzns)
        self.jzns_nmlf.setObjectName("jzns_nmlf")
        self.verticalLayout_7.addWidget(self.jzns_nmlf)
        self.jzns_nmlz = QtWidgets.QRadioButton(self.jzns)
        self.jzns_nmlz.setObjectName("jzns_nmlz")
        self.verticalLayout_7.addWidget(self.jzns_nmlz)
        self.horizontalLayout_3.addWidget(self.jzns)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(2, 3)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_5 = QtWidgets.QLabel(WMML_prep)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(0, 32))
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 32))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.jz_fd_tab = QtWidgets.QTableView(WMML_prep)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.jz_fd_tab.sizePolicy().hasHeightForWidth())
        self.jz_fd_tab.setSizePolicy(sizePolicy)
        self.jz_fd_tab.setSizeIncrement(QtCore.QSize(0, 20))
        self.jz_fd_tab.setObjectName("jz_fd_tab")
        self.verticalLayout_3.addWidget(self.jz_fd_tab)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_7 = QtWidgets.QLabel(WMML_prep)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMinimumSize(QtCore.QSize(0, 32))
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 32))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_4.addWidget(self.label_7)
        self.jz_td_tab = QtWidgets.QTableView(WMML_prep)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.jz_td_tab.sizePolicy().hasHeightForWidth())
        self.jz_td_tab.setSizePolicy(sizePolicy)
        self.jz_td_tab.setSizeIncrement(QtCore.QSize(0, 20))
        self.jz_td_tab.setObjectName("jz_td_tab")
        self.verticalLayout_4.addWidget(self.jz_td_tab)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.horizontalLayout_2.setStretch(0, 6)
        self.horizontalLayout_2.setStretch(1, 2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.verticalLayout_6.setStretch(0, 1)
        self.verticalLayout_6.setStretch(1, 3)
        self.gridLayout.addLayout(self.verticalLayout_6, 0, 0, 1, 1)
        self.infobox = QtWidgets.QLabel(WMML_prep)
        self.infobox.setObjectName("infobox")
        self.gridLayout.addWidget(self.infobox, 1, 0, 1, 1)

        self.retranslateUi(WMML_prep)
        self.jzns.clicked['bool'].connect(self.jzfucbx.setDisabled)
        self.jzns.clicked['bool'].connect(self.jzadfun.setDisabled)
        self.jzns.clicked['bool'].connect(self.jzadfb.setDisabled)
        self.jzns.clicked['bool'].connect(self.jzfuncedit.setDisabled)
        QtCore.QMetaObject.connectSlotsByName(WMML_prep)

    def retranslateUi(self, WMML_prep):
        _translate = QtCore.QCoreApplication.translate
        WMML_prep.setWindowTitle(_translate("WMML_prep", "WMMLprep"))
        self.label.setText(_translate("WMML_prep", "Select Function"))
        self.jzfucbx.setItemText(0, _translate("WMML_prep", "Ln"))
        self.jzfucbx.setItemText(1, _translate("WMML_prep", "Log10"))
        self.jzfucbx.setItemText(2, _translate("WMML_prep", "Log2"))
        self.jzfucbx.setItemText(3, _translate("WMML_prep", "Sin"))
        self.jzfucbx.setItemText(4, _translate("WMML_prep", "Cos"))
        self.jzfucbx.setItemText(5, _translate("WMML_prep", "Tan"))
        self.jzfucbx.setItemText(6, _translate("WMML_prep", "Exp"))
        self.jzfucbx.setItemText(7, _translate("WMML_prep", "Arctan"))
        self.jzfucbx.setItemText(8, _translate("WMML_prep", "Arcsin"))
        self.jzfucbx.setItemText(9, _translate("WMML_prep", "Arccos"))
        self.jzadfun.setText(_translate("WMML_prep", "Add Function"))
        self.jzadfb.setText(_translate("WMML_prep", "Add Feature"))
        self.jzcptfb.setText(_translate("WMML_prep", "Compute"))
        self.jzsdf.setText(_translate("WMML_prep", "Send Data"))
        self.label_3.setText(_translate("WMML_prep", "New Feature Name"))
        self.label_4.setText(_translate("WMML_prep", "Expression"))
        self.jzns.setTitle(_translate("WMML_prep", "Normalize Selection"))
        self.jzns_std.setText(_translate("WMML_prep", "Standardize to μ=0,σ²=1"))
        self.jzns_ctr.setText(_translate("WMML_prep", "Center to μ=0"))
        self.jzns_sle.setText(_translate("WMML_prep", "Scale to σ²=1"))
        self.jzns_nmlf.setText(_translate("WMML_prep", "Normalize to  interval [-1,1]"))
        self.jzns_nmlz.setText(_translate("WMML_prep", "Normalize to  interval [0,1]"))
        self.label_5.setText(_translate("WMML_prep", "Selected Feature"))
        self.label_7.setText(_translate("WMML_prep", "Target Variable"))
        self.infobox.setText(_translate("WMML_prep", "....."))
