from PyQt5 import QtCore, QtGui, QtWidgets


# noinspection PyUnresolvedReferences
class Ui_WMML_nn(object):
    def setupUi(self, WMML_nn):
        WMML_nn.setObjectName("WMML_nn")
        WMML_nn.resize(593, 647)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(WMML_nn.sizePolicy().hasHeightForWidth())
        WMML_nn.setSizePolicy(sizePolicy)
        WMML_nn.setMinimumSize(QtCore.QSize(593, 647))
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(WMML_nn)
        self.horizontalLayout_7.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.groupBox = QtWidgets.QGroupBox(WMML_nn)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(241, 511))
        self.groupBox.setMaximumSize(QtCore.QSize(241, 511))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.pshl = QtWidgets.QComboBox(self.groupBox)
        self.pshl.setObjectName("pshl")
        self.pshl.addItem("")
        self.pshl.addItem("")
        self.pshl.addItem("")
        self.pshl.addItem("")
        self.pshl.addItem("")
        self.horizontalLayout.addWidget(self.pshl)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.ps_hls_3 = QtWidgets.QLineEdit(self.groupBox)
        self.ps_hls_3.setObjectName("ps_hls_3")
        self.gridLayout.addWidget(self.ps_hls_3, 1, 2, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.groupBox)
        self.label_25.setObjectName("label_25")
        self.gridLayout.addWidget(self.label_25, 0, 0, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.groupBox)
        self.label_23.setObjectName("label_23")
        self.gridLayout.addWidget(self.label_23, 0, 1, 1, 1)
        self.ps_hls_4 = QtWidgets.QLineEdit(self.groupBox)
        self.ps_hls_4.setObjectName("ps_hls_4")
        self.gridLayout.addWidget(self.ps_hls_4, 1, 3, 1, 1)
        self.ps_hls = QtWidgets.QLineEdit(self.groupBox)
        self.ps_hls.setObjectName("ps_hls")
        self.gridLayout.addWidget(self.ps_hls, 1, 0, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.groupBox)
        self.label_26.setObjectName("label_26")
        self.gridLayout.addWidget(self.label_26, 0, 2, 1, 1)
        self.ps_hls_2 = QtWidgets.QLineEdit(self.groupBox)
        self.ps_hls_2.setObjectName("ps_hls_2")
        self.gridLayout.addWidget(self.ps_hls_2, 1, 1, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.groupBox)
        self.label_27.setObjectName("label_27")
        self.gridLayout.addWidget(self.label_27, 0, 3, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.groupBox)
        self.label_24.setObjectName("label_24")
        self.gridLayout.addWidget(self.label_24, 0, 4, 1, 1)
        self.ps_hls_5 = QtWidgets.QLineEdit(self.groupBox)
        self.ps_hls_5.setObjectName("ps_hls_5")
        self.gridLayout.addWidget(self.ps_hls_5, 1, 4, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.ps_a_ident = QtWidgets.QRadioButton(self.groupBox_4)
        self.ps_a_ident.setChecked(False)
        self.ps_a_ident.setObjectName("ps_a_ident")
        self.gridLayout_3.addWidget(self.ps_a_ident, 0, 0, 1, 1)
        self.ps_a_tanh = QtWidgets.QRadioButton(self.groupBox_4)
        self.ps_a_tanh.setObjectName("ps_a_tanh")
        self.gridLayout_3.addWidget(self.ps_a_tanh, 0, 1, 1, 1)
        self.ps_a_log = QtWidgets.QRadioButton(self.groupBox_4)
        self.ps_a_log.setChecked(False)
        self.ps_a_log.setObjectName("ps_a_log")
        self.gridLayout_3.addWidget(self.ps_a_log, 1, 0, 1, 1)
        self.ps_a_relu = QtWidgets.QRadioButton(self.groupBox_4)
        self.ps_a_relu.setChecked(True)
        self.ps_a_relu.setObjectName("ps_a_relu")
        self.gridLayout_3.addWidget(self.ps_a_relu, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_4)
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_6.setObjectName("groupBox_6")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ps_s_lbfgs = QtWidgets.QRadioButton(self.groupBox_6)
        self.ps_s_lbfgs.setChecked(False)
        self.ps_s_lbfgs.setObjectName("ps_s_lbfgs")
        self.horizontalLayout_2.addWidget(self.ps_s_lbfgs)
        self.ps_s_sgd = QtWidgets.QRadioButton(self.groupBox_6)
        self.ps_s_sgd.setObjectName("ps_s_sgd")
        self.horizontalLayout_2.addWidget(self.ps_s_sgd)
        self.ps_s_adam = QtWidgets.QRadioButton(self.groupBox_6)
        self.ps_s_adam.setChecked(True)
        self.ps_s_adam.setObjectName("ps_s_adam")
        self.horizontalLayout_2.addWidget(self.ps_s_adam)
        self.verticalLayout.addWidget(self.groupBox_6)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 2, 0, 1, 1)
        self.ps_bs_m = QtWidgets.QLineEdit(self.groupBox)
        self.ps_bs_m.setObjectName("ps_bs_m")
        self.gridLayout_2.addWidget(self.ps_bs_m, 0, 1, 1, 1)
        self.ps_alpha = QtWidgets.QLineEdit(self.groupBox)
        self.ps_alpha.setObjectName("ps_alpha")
        self.gridLayout_2.addWidget(self.ps_alpha, 1, 1, 1, 1)
        self.ps_tol = QtWidgets.QLineEdit(self.groupBox)
        self.ps_tol.setObjectName("ps_tol")
        self.gridLayout_2.addWidget(self.ps_tol, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 3, 0, 1, 1)
        self.ps_iter = QtWidgets.QLineEdit(self.groupBox)
        self.ps_iter.setObjectName("ps_iter")
        self.gridLayout_2.addWidget(self.ps_iter, 3, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.groupBox_8 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_8.setCheckable(True)
        self.groupBox_8.setChecked(False)
        self.groupBox_8.setObjectName("groupBox_8")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_8)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.groupBox_8)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.ps_es_vsf = QtWidgets.QLineEdit(self.groupBox_8)
        self.ps_es_vsf.setObjectName("ps_es_vsf")
        self.verticalLayout_2.addWidget(self.ps_es_vsf)
        self.verticalLayout.addWidget(self.groupBox_8)
        self.verticalLayout_5.addWidget(self.groupBox)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.jzsdf = QtWidgets.QPushButton(WMML_nn)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.jzsdf.setFont(font)
        self.jzsdf.setObjectName("jzsdf")
        self.verticalLayout_5.addWidget(self.jzsdf)
        self.infobox = QtWidgets.QLabel(WMML_nn)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.infobox.setFont(font)
        self.infobox.setObjectName("infobox")
        self.verticalLayout_5.addWidget(self.infobox)
        self.horizontalLayout_7.addLayout(self.verticalLayout_5)
        self.groupBox_9 = QtWidgets.QGroupBox(WMML_nn)
        self.groupBox_9.setMinimumSize(QtCore.QSize(321, 625))
        self.groupBox_9.setMaximumSize(QtCore.QSize(321, 625))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.groupBox_9.setFont(font)
        self.groupBox_9.setCheckable(True)
        self.groupBox_9.setChecked(False)
        self.groupBox_9.setObjectName("groupBox_9")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_9)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox_9)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.hss_tol_max = QtWidgets.QLineEdit(self.groupBox_2)
        self.hss_tol_max.setObjectName("hss_tol_max")
        self.gridLayout_4.addWidget(self.hss_tol_max, 1, 2, 1, 1)
        self.hss_iter_max = QtWidgets.QLineEdit(self.groupBox_2)
        self.hss_iter_max.setObjectName("hss_iter_max")
        self.gridLayout_4.addWidget(self.hss_iter_max, 2, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setObjectName("label_9")
        self.gridLayout_4.addWidget(self.label_9, 1, 0, 1, 1)
        self.hss_iter_min = QtWidgets.QLineEdit(self.groupBox_2)
        self.hss_iter_min.setObjectName("hss_iter_min")
        self.gridLayout_4.addWidget(self.hss_iter_min, 2, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.groupBox_2)
        self.label_16.setObjectName("label_16")
        self.gridLayout_4.addWidget(self.label_16, 0, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.groupBox_2)
        self.label_17.setObjectName("label_17")
        self.gridLayout_4.addWidget(self.label_17, 0, 2, 1, 1)
        self.hss_tol_min = QtWidgets.QLineEdit(self.groupBox_2)
        self.hss_tol_min.setObjectName("hss_tol_min")
        self.gridLayout_4.addWidget(self.hss_tol_min, 1, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_2)
        self.label_12.setObjectName("label_12")
        self.gridLayout_4.addWidget(self.label_12, 2, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox_2)
        self.label_13.setObjectName("label_13")
        self.gridLayout_4.addWidget(self.label_13, 3, 0, 1, 1)
        self.hss_bs_min = QtWidgets.QLineEdit(self.groupBox_2)
        self.hss_bs_min.setInputMask("")
        self.hss_bs_min.setObjectName("hss_bs_min")
        self.gridLayout_4.addWidget(self.hss_bs_min, 3, 1, 1, 1)
        self.hss_bs_max = QtWidgets.QLineEdit(self.groupBox_2)
        self.hss_bs_max.setInputMask("")
        self.hss_bs_max.setMaxLength(32767)
        self.hss_bs_max.setObjectName("hss_bs_max")
        self.gridLayout_4.addWidget(self.hss_bs_max, 3, 2, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_4)
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.hss_a_ident = QtWidgets.QCheckBox(self.groupBox_5)
        self.hss_a_ident.setChecked(True)
        self.hss_a_ident.setObjectName("hss_a_ident")
        self.gridLayout_6.addWidget(self.hss_a_ident, 0, 0, 1, 1)
        self.hss_a_tanh = QtWidgets.QCheckBox(self.groupBox_5)
        self.hss_a_tanh.setChecked(True)
        self.hss_a_tanh.setObjectName("hss_a_tanh")
        self.gridLayout_6.addWidget(self.hss_a_tanh, 0, 1, 1, 1)
        self.hss_a_log = QtWidgets.QCheckBox(self.groupBox_5)
        self.hss_a_log.setChecked(True)
        self.hss_a_log.setObjectName("hss_a_log")
        self.gridLayout_6.addWidget(self.hss_a_log, 1, 0, 1, 1)
        self.hss_a_relu = QtWidgets.QCheckBox(self.groupBox_5)
        self.hss_a_relu.setChecked(True)
        self.hss_a_relu.setObjectName("hss_a_relu")
        self.gridLayout_6.addWidget(self.hss_a_relu, 1, 1, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_5)
        self.groupBox_10 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_10.setCheckable(False)
        self.groupBox_10.setChecked(False)
        self.groupBox_10.setObjectName("groupBox_10")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox_10)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.hss_s_sgd = QtWidgets.QCheckBox(self.groupBox_10)
        self.hss_s_sgd.setChecked(True)
        self.hss_s_sgd.setObjectName("hss_s_sgd")
        self.horizontalLayout_4.addWidget(self.hss_s_sgd)
        self.hss_s_adam = QtWidgets.QCheckBox(self.groupBox_10)
        self.hss_s_adam.setChecked(True)
        self.hss_s_adam.setObjectName("hss_s_adam")
        self.horizontalLayout_4.addWidget(self.hss_s_adam)
        self.hss_s_lbfgs = QtWidgets.QCheckBox(self.groupBox_10)
        self.hss_s_lbfgs.setChecked(True)
        self.hss_s_lbfgs.setObjectName("hss_s_lbfgs")
        self.horizontalLayout_4.addWidget(self.hss_s_lbfgs)
        self.verticalLayout_3.addWidget(self.groupBox_10)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        self.hsshl = QtWidgets.QComboBox(self.groupBox_2)
        self.hsshl.setObjectName("hsshl")
        self.hsshl.addItem("")
        self.hsshl.addItem("")
        self.hsshl.addItem("")
        self.hsshl.addItem("")
        self.hsshl.addItem("")
        self.horizontalLayout_3.addWidget(self.hsshl)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_19 = QtWidgets.QLabel(self.groupBox_2)
        self.label_19.setObjectName("label_19")
        self.gridLayout_5.addWidget(self.label_19, 1, 0, 1, 1)
        self.hss_hls_min = QtWidgets.QLineEdit(self.groupBox_2)
        self.hss_hls_min.setObjectName("hss_hls_min")
        self.gridLayout_5.addWidget(self.hss_hls_min, 1, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setObjectName("label_11")
        self.gridLayout_5.addWidget(self.label_11, 0, 2, 1, 1)
        self.hss_hls_min_2 = QtWidgets.QLineEdit(self.groupBox_2)
        self.hss_hls_min_2.setObjectName("hss_hls_min_2")
        self.gridLayout_5.addWidget(self.hss_hls_min_2, 1, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setObjectName("label_10")
        self.gridLayout_5.addWidget(self.label_10, 0, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.groupBox_2)
        self.label_18.setObjectName("label_18")
        self.gridLayout_5.addWidget(self.label_18, 0, 3, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.groupBox_2)
        self.label_22.setObjectName("label_22")
        self.gridLayout_5.addWidget(self.label_22, 0, 5, 1, 1)
        self.hss_hls_min_3 = QtWidgets.QLineEdit(self.groupBox_2)
        self.hss_hls_min_3.setObjectName("hss_hls_min_3")
        self.gridLayout_5.addWidget(self.hss_hls_min_3, 1, 3, 1, 1)
        self.hss_hls_min_5 = QtWidgets.QLineEdit(self.groupBox_2)
        self.hss_hls_min_5.setObjectName("hss_hls_min_5")
        self.gridLayout_5.addWidget(self.hss_hls_min_5, 1, 5, 1, 1)
        self.hss_hls_min_4 = QtWidgets.QLineEdit(self.groupBox_2)
        self.hss_hls_min_4.setObjectName("hss_hls_min_4")
        self.gridLayout_5.addWidget(self.hss_hls_min_4, 1, 4, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.groupBox_2)
        self.label_21.setObjectName("label_21")
        self.gridLayout_5.addWidget(self.label_21, 0, 4, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.groupBox_2)
        self.label_20.setObjectName("label_20")
        self.gridLayout_5.addWidget(self.label_20, 2, 0, 1, 1)
        self.hss_hls_max = QtWidgets.QLineEdit(self.groupBox_2)
        self.hss_hls_max.setObjectName("hss_hls_max")
        self.gridLayout_5.addWidget(self.hss_hls_max, 2, 1, 1, 1)
        self.hss_hls_max_2 = QtWidgets.QLineEdit(self.groupBox_2)
        self.hss_hls_max_2.setObjectName("hss_hls_max_2")
        self.gridLayout_5.addWidget(self.hss_hls_max_2, 2, 2, 1, 1)
        self.hss_hls_max_3 = QtWidgets.QLineEdit(self.groupBox_2)
        self.hss_hls_max_3.setObjectName("hss_hls_max_3")
        self.gridLayout_5.addWidget(self.hss_hls_max_3, 2, 3, 1, 1)
        self.hss_hls_max_4 = QtWidgets.QLineEdit(self.groupBox_2)
        self.hss_hls_max_4.setObjectName("hss_hls_max_4")
        self.gridLayout_5.addWidget(self.hss_hls_max_4, 2, 4, 1, 1)
        self.hss_hls_max_5 = QtWidgets.QLineEdit(self.groupBox_2)
        self.hss_hls_max_5.setObjectName("hss_hls_max_5")
        self.gridLayout_5.addWidget(self.hss_hls_max_5, 2, 5, 1, 1)
        self.gridLayout_5.setRowStretch(0, 1)
        self.gridLayout_5.setRowStretch(1, 1)
        self.gridLayout_5.setRowStretch(2, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_5)
        self.verticalLayout_6.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox_9)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox_7 = QtWidgets.QGroupBox(self.groupBox_3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.groupBox_7.setFont(font)
        self.groupBox_7.setCheckable(False)
        self.groupBox_7.setChecked(False)
        self.groupBox_7.setObjectName("groupBox_7")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.groupBox_7)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.ms_tpeButton = QtWidgets.QRadioButton(self.groupBox_7)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.ms_tpeButton.setFont(font)
        self.ms_tpeButton.setChecked(True)
        self.ms_tpeButton.setObjectName("ms_tpeButton")
        self.horizontalLayout_6.addWidget(self.ms_tpeButton)
        self.ms_saButton = QtWidgets.QRadioButton(self.groupBox_7)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.ms_saButton.setFont(font)
        self.ms_saButton.setObjectName("ms_saButton")
        self.horizontalLayout_6.addWidget(self.ms_saButton)
        self.ms_rsaButton = QtWidgets.QRadioButton(self.groupBox_7)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.ms_rsaButton.setFont(font)
        self.ms_rsaButton.setObjectName("ms_rsaButton")
        self.horizontalLayout_6.addWidget(self.ms_rsaButton)
        self.verticalLayout_4.addWidget(self.groupBox_7)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_14 = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_5.addWidget(self.label_14)
        self.hss_times = QtWidgets.QLineEdit(self.groupBox_3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.hss_times.setFont(font)
        self.hss_times.setObjectName("hss_times")
        self.horizontalLayout_5.addWidget(self.hss_times)
        self.label_15 = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_5.addWidget(self.label_15)
        self.hss_fd = QtWidgets.QComboBox(self.groupBox_3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.hss_fd.setFont(font)
        self.hss_fd.setObjectName("hss_fd")
        self.hss_fd.addItem("")
        self.hss_fd.addItem("")
        self.hss_fd.addItem("")
        self.hss_fd.addItem("")
        self.hss_fd.addItem("")
        self.horizontalLayout_5.addWidget(self.hss_fd)
        self.horizontalLayout_5.setStretch(0, 1)
        self.horizontalLayout_5.setStretch(1, 1)
        self.horizontalLayout_5.setStretch(2, 1)
        self.horizontalLayout_5.setStretch(3, 1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.verticalLayout_6.addWidget(self.groupBox_3)
        self.horizontalLayout_7.addWidget(self.groupBox_9)

        self.retranslateUi(WMML_nn)
        QtCore.QMetaObject.connectSlotsByName(WMML_nn)

    def retranslateUi(self, WMML_nn):
        _translate = QtCore.QCoreApplication.translate
        WMML_nn.setWindowTitle(_translate("WMML_nn", "WMMLnn"))
        self.groupBox.setTitle(_translate("WMML_nn", "Model Parameters"))
        self.label_2.setText(_translate("WMML_nn", "Layer Depth"))
        self.pshl.setItemText(0, _translate("WMML_nn", "1"))
        self.pshl.setItemText(1, _translate("WMML_nn", "2"))
        self.pshl.setItemText(2, _translate("WMML_nn", "3"))
        self.pshl.setItemText(3, _translate("WMML_nn", "4"))
        self.pshl.setItemText(4, _translate("WMML_nn", "5"))
        self.ps_hls_3.setText(_translate("WMML_nn", "8"))
        self.ps_hls_3.setPlaceholderText(_translate("WMML_nn", "8"))
        self.label_25.setText(_translate("WMML_nn", "L1"))
        self.label_23.setText(_translate("WMML_nn", "L2"))
        self.ps_hls_4.setText(_translate("WMML_nn", "8"))
        self.ps_hls_4.setPlaceholderText(_translate("WMML_nn", "8"))
        self.ps_hls.setText(_translate("WMML_nn", "8"))
        self.ps_hls.setPlaceholderText(_translate("WMML_nn", "8"))
        self.label_26.setText(_translate("WMML_nn", "L3"))
        self.ps_hls_2.setText(_translate("WMML_nn", "8"))
        self.ps_hls_2.setPlaceholderText(_translate("WMML_nn", "8"))
        self.label_27.setText(_translate("WMML_nn", "L4"))
        self.label_24.setText(_translate("WMML_nn", "L5"))
        self.ps_hls_5.setText(_translate("WMML_nn", "8"))
        self.ps_hls_5.setPlaceholderText(_translate("WMML_nn", "8"))
        self.groupBox_4.setTitle(_translate("WMML_nn", "Activation Function"))
        self.ps_a_ident.setText(_translate("WMML_nn", "Identity"))
        self.ps_a_tanh.setText(_translate("WMML_nn", "Tanh"))
        self.ps_a_log.setText(_translate("WMML_nn", "Logistic"))
        self.ps_a_relu.setText(_translate("WMML_nn", "Relu"))
        self.groupBox_6.setTitle(_translate("WMML_nn", "Solver"))
        self.ps_s_lbfgs.setText(_translate("WMML_nn", "lbfgs"))
        self.ps_s_sgd.setText(_translate("WMML_nn", "SGD"))
        self.ps_s_adam.setText(_translate("WMML_nn", "Adam"))
        self.label_7.setText(_translate("WMML_nn", "Tolerance"))
        self.ps_bs_m.setText(_translate("WMML_nn", "auto"))
        self.ps_bs_m.setPlaceholderText(_translate("WMML_nn", "auto"))
        self.ps_alpha.setText(_translate("WMML_nn", "0.0001"))
        self.ps_alpha.setPlaceholderText(_translate("WMML_nn", "0.0001"))
        self.ps_tol.setText(_translate("WMML_nn", "0.0001"))
        self.ps_tol.setPlaceholderText(_translate("WMML_nn", "0.0001"))
        self.label_4.setText(_translate("WMML_nn", "Batch Size"))
        self.label_3.setText(_translate("WMML_nn", "Alpha"))
        self.label_8.setText(_translate("WMML_nn", "Max Iteration"))
        self.ps_iter.setText(_translate("WMML_nn", "200"))
        self.ps_iter.setPlaceholderText(_translate("WMML_nn", "200"))
        self.groupBox_8.setTitle(_translate("WMML_nn", "Early Stopping"))
        self.label_5.setText(_translate("WMML_nn", "Validation Fraction"))
        self.ps_es_vsf.setText(_translate("WMML_nn", "0.1"))
        self.ps_es_vsf.setPlaceholderText(_translate("WMML_nn", "0.1"))
        self.jzsdf.setText(_translate("WMML_nn", "Send Model"))
        self.infobox.setText(_translate("WMML_nn", "....."))
        self.groupBox_9.setTitle(_translate("WMML_nn", "Enable Optimazation"))
        self.groupBox_2.setTitle(_translate("WMML_nn", "Space"))
        self.hss_tol_max.setText(_translate("WMML_nn", "0.01"))
        self.hss_tol_max.setPlaceholderText(_translate("WMML_nn", "0.01"))
        self.hss_iter_max.setText(_translate("WMML_nn", "1000"))
        self.hss_iter_max.setPlaceholderText(_translate("WMML_nn", "1000"))
        self.label_9.setText(_translate("WMML_nn", "Tolerance"))
        self.hss_iter_min.setText(_translate("WMML_nn", "20"))
        self.hss_iter_min.setPlaceholderText(_translate("WMML_nn", "20"))
        self.label_16.setText(_translate("WMML_nn", "Min"))
        self.label_17.setText(_translate("WMML_nn", "Max"))
        self.hss_tol_min.setText(_translate("WMML_nn", "0.00001"))
        self.hss_tol_min.setPlaceholderText(_translate("WMML_nn", "0.00001"))
        self.label_12.setText(_translate("WMML_nn", "Max Iteration"))
        self.label_13.setText(_translate("WMML_nn", "Batch Size"))
        self.hss_bs_min.setText(_translate("WMML_nn", "2"))
        self.hss_bs_min.setPlaceholderText(_translate("WMML_nn", "2"))
        self.hss_bs_max.setText(_translate("WMML_nn", "200"))
        self.hss_bs_max.setPlaceholderText(_translate("WMML_nn", "200"))
        self.groupBox_5.setTitle(_translate("WMML_nn", "Activation Function"))
        self.hss_a_ident.setText(_translate("WMML_nn", "Identity"))
        self.hss_a_tanh.setText(_translate("WMML_nn", "Tanh"))
        self.hss_a_log.setText(_translate("WMML_nn", "Logistic"))
        self.hss_a_relu.setText(_translate("WMML_nn", "Relu"))
        self.groupBox_10.setTitle(_translate("WMML_nn", "Solver"))
        self.hss_s_sgd.setText(_translate("WMML_nn", "SGD"))
        self.hss_s_adam.setText(_translate("WMML_nn", "Adam"))
        self.hss_s_lbfgs.setText(_translate("WMML_nn", "lbfgs"))
        self.label_6.setText(_translate("WMML_nn", "Layer Depth"))
        self.hsshl.setItemText(0, _translate("WMML_nn", "1"))
        self.hsshl.setItemText(1, _translate("WMML_nn", "2"))
        self.hsshl.setItemText(2, _translate("WMML_nn", "3"))
        self.hsshl.setItemText(3, _translate("WMML_nn", "4"))
        self.hsshl.setItemText(4, _translate("WMML_nn", "5"))
        self.label_19.setText(_translate("WMML_nn", "Min"))
        self.hss_hls_min.setText(_translate("WMML_nn", "4"))
        self.hss_hls_min.setPlaceholderText(_translate("WMML_nn", "4"))
        self.label_11.setText(_translate("WMML_nn", "L2"))
        self.hss_hls_min_2.setText(_translate("WMML_nn", "4"))
        self.hss_hls_min_2.setPlaceholderText(_translate("WMML_nn", "4"))
        self.label_10.setText(_translate("WMML_nn", "L1"))
        self.label_18.setText(_translate("WMML_nn", "L3"))
        self.label_22.setText(_translate("WMML_nn", "L5"))
        self.hss_hls_min_3.setText(_translate("WMML_nn", "4"))
        self.hss_hls_min_3.setPlaceholderText(_translate("WMML_nn", "4"))
        self.hss_hls_min_5.setText(_translate("WMML_nn", "2"))
        self.hss_hls_min_5.setPlaceholderText(_translate("WMML_nn", "2"))
        self.hss_hls_min_4.setText(_translate("WMML_nn", "4"))
        self.hss_hls_min_4.setPlaceholderText(_translate("WMML_nn", "4"))
        self.label_21.setText(_translate("WMML_nn", "L4"))
        self.label_20.setText(_translate("WMML_nn", "Max"))
        self.hss_hls_max.setText(_translate("WMML_nn", "16"))
        self.hss_hls_max.setPlaceholderText(_translate("WMML_nn", "16"))
        self.hss_hls_max_2.setText(_translate("WMML_nn", "16"))
        self.hss_hls_max_2.setPlaceholderText(_translate("WMML_nn", "16"))
        self.hss_hls_max_3.setText(_translate("WMML_nn", "16"))
        self.hss_hls_max_3.setPlaceholderText(_translate("WMML_nn", "16"))
        self.hss_hls_max_4.setText(_translate("WMML_nn", "8"))
        self.hss_hls_max_4.setPlaceholderText(_translate("WMML_nn", "8"))
        self.hss_hls_max_5.setText(_translate("WMML_nn", "4"))
        self.hss_hls_max_5.setPlaceholderText(_translate("WMML_nn", "4"))
        self.groupBox_3.setTitle(_translate("WMML_nn", "Parameters"))
        self.groupBox_7.setTitle(_translate("WMML_nn", "Algorithms"))
        self.ms_tpeButton.setText(_translate("WMML_nn", "TPE"))
        self.ms_saButton.setText(_translate("WMML_nn", "Adaptive"))
        self.ms_rsaButton.setText(_translate("WMML_nn", "Random"))
        self.label_14.setText(_translate("WMML_nn", "Times"))
        self.hss_times.setText(_translate("WMML_nn", "20"))
        self.hss_times.setPlaceholderText(_translate("WMML_nn", "20"))
        self.label_15.setText(_translate("WMML_nn", "Folds"))
        self.hss_fd.setItemText(0, _translate("WMML_nn", "2"))
        self.hss_fd.setItemText(1, _translate("WMML_nn", "3"))
        self.hss_fd.setItemText(2, _translate("WMML_nn", "5"))
        self.hss_fd.setItemText(3, _translate("WMML_nn", "10"))
        self.hss_fd.setItemText(4, _translate("WMML_nn", "20"))
